In [1]:
import numpy as np
import random


In [83]:

def sigmoid(Z):
    output = 1 / (1 + np.exp(-Z))
    return output

#This function creates the length and coordinates of the bugs
def initialize_intellect_coordinates(length_of_intellect,random_seed,data_length,num_data):#length of the food. 
    random.seed(random_seed)
    
    intellect = {}
    intellect["coordinates"] = np.ones((4,1))
    intellect["W1"] = np.random.randn(length_of_intellect,data_length)
    intellect["b1"] = np.zeros((length_of_intellect,1))
    intellect["W2"] = np.random.randn(4,length_of_intellect)
    intellect["b2"] = np.zeros((4,1))
    intellect["decider_W3"] = np.random.randn(1,num_data)
    intellect["decider_b3"] = np.zeros((1,1))
    intellect["score"] = 0
    intellect["distance_list"] = []
    return intellect 

#This function creates as many bugs as we want.
def make_bugs(random_seed,num_bugs,length_of_intellect,data_length,num_data):
    random.seed(3)
    bugs = {}
    for i in range(0,num_bugs):
        bugs["bug" + str(i)] = initialize_intellect_coordinates(length_of_intellect,i,data_length,num_data)

    return bugs

#This function give us the inherent features of food and the coordinates of the food.
def initialize_food(random_seed):
    random.seed(random_seed)
    food_features = {}
    food_features["coordinates"] = np.random.randn(4,1) 
    food_features["chemical_volatility"] = np.random.randn(4,1)
    #food_features["merged"] = np.append(food_features["coordinates"] ,food_features["chemical_volatility"])
    return food_features["coordinates"]#food_features["merged"]

#This fuınction create foods as much as we want
def make_food(num_food):
    random.seed(4)
    food = {}
    for f in range(0,num_food):
        food["fo" + str(f)] = initialize_food(f)
    return food

#This function describes the act of a bug thinking of which route to take.
def bug_deciding(bug_name,bugs,food):
    bugy = bugs[str(bug_name)]["coordinates"]
    W1 = bugs[str(bug_name)]["W1"]
    b1 = bugs[str(bug_name)]["b1"]
    W2 = bugs[str(bug_name)]["W2"]
    b2 = bugs[str(bug_name)]["b2"]
    decider_W3 = bugs[str(bug_name)]["decider_W3"]
    decider_b3 = bugs[str(bug_name)]["decider_b3"]
    
    a = food["fo" + str(0)]
    a = a.reshape(a.shape[0],1)
    #print("a is :",a)
    for i in range(1,len(food)):
        b = food["fo"+ str(i)]
        b = b.reshape(b.shape[0],1)
        #print("b is:" , b)
        a = np.append(a,b,axis = 1)
    
    k = np.ones([a.shape[0],a.shape[1]])
    #print("k is: " , k)
    second = k * bugy
    #print("second is : ",second)
    a = np.append(a,second,axis = 0)    
    
    #print("result : ",a)
   
    #this part is the forward propagation part
    
    Z1 = np.dot(W1,a) + b1
    A1 = Z1
    Z2 = np.dot(W2,A1) + b2
    A2 = Z2
    Z3 = np.dot(decider_W3,A2.T) + decider_b3
    AL = Z3
    #so as a result bug looks at all of the data. And returns an array the size(4,#data)
    #So we need to also make it another decision like which way you will pick.
    #we will make a single layer neural network
    return AL.T
    
#This function generalizes deciding to all the bugs
def all_the_bugs_deciding(bugs,food):
    movement_points = {}
    for k in range(len(bugs)):
        movement_points["bug" + str(k)] = bug_deciding("bug" + str(k) , bugs,food)
        
    return movement_points
        

    
#This function let s bugs do their thought moves.    
def move_all_the_bugs(bugs,movement_points):
    for i in range(len(bugs)):
        bugs["bug" + str(i)]["coordinates"] = bugs["bug" + str(i)]["coordinates"] +  movement_points["bug" + str(i)]
    return bugs
  
def evaluating_bugs(bugs,food):
#take a bug and calculate it s distance from all the food. 
    
    for i in range(len(bugs)):
        distance_list = bugs["bug" + str(i)]["distance_list"]
        for j in range(len(food)):
            vector_dif = bugs["bug" + str(i)]["coordinates"] - food["fo" + str(j)]
            distance = (np.dot(vector_dif.T,vector_dif))** 0.5
            distance_list.append(distance)
        bugs["bug" + str(i)]["score"] = min(distance_list)
        bugs["bug" + str(i)]["distance_list"] = []
    
            
        
        
def natural_selection(bugs,food,surv_num = 4):#The top two bugs that get closest to the food gives birth to next generation.
#This function will calculate distance of the bugs to the closest food resources and the closest ones are rewarded with reproduction rights.
#get the coordinate of bug 1 , find distances for all the food,
    evaluating_bugs(bugs,food)
    
    bug_score = {}
    
    for i in range(len(bugs)):
    
        bug_score["bug" + str(i)] = bugs["bug" + str(i)]["score"]
        
    score_sorted = sorted(bug_score.items(), key = lambda x:x[1],reverse=False)
    
    survivor_num = len(bugs) // surv_num
    
    survivors = score_sorted[0:survivor_num]
    survivor_names = []
    for s in range(len(survivors)):
        survivor_names.append(survivors[s][0])
        
    
    return survivor_names

def single_cell_shuffle(bugs,survivor_names,gene_bag):
    #take bug0 and capture all of their cells for layer 1. And then put them in a dictionary for layers
    #bugn cells in layer 1 go to layer_1_cells dictionary.
    #bugn cells in layer 2 go to layer_2_cells dictionary.
    
    gene_bag["layer_1_cells_W1"] = []
    gene_bag["layer_1_cells_b1"] = []
    gene_bag["layer_2_cells_W2"] = []
    gene_bag["layer_2_cells_b2"] = []
    gene_bag["layer_3_cells_W3"] = []
    gene_bag["layer_3_cells_b3"] = []
    for i in range(len(survivor_names)):
        for s in range(len(bugs["bug0"]["W1"])):
            gene_bag["layer_1_cells_W1"].append(bugs[survivor_names[i]]["W1"][s,:])
    for i in range(len(survivor_names)):
        for s in range(len(bugs["bug0"]["b1"])):
            gene_bag["layer_1_cells_b1"].append(bugs[survivor_names[i]]["b1"][s,:])
            
    for i in range(len(survivor_names)):
        for s in range(len(bugs["bug0"]["W2"])):
            gene_bag["layer_2_cells_W2"].append(bugs[survivor_names[i]]["W2"][s,:])
    
    for i in range(len(survivor_names)):
        for s in range(len(bugs["bug0"]["b2"])):
            gene_bag["layer_2_cells_b2"].append(bugs[survivor_names[i]]["b2"][s,:])
    
    for i in range(len(survivor_names)):
        for s in range(len(bugs["bug0"]["decider_W3"])):
            gene_bag["layer_3_cells_W3"].append(bugs[survivor_names[i]]["decider_W3"][s,:])
    
    for i in range(len(survivor_names)):
        for s in range(len(bugs["bug0"]["decider_b3"])):
            gene_bag["layer_3_cells_b3"].append(bugs[survivor_names[i]]["decider_b3"][s,:])
    
    
    return gene_bag

def two_cell_shuffle(bugs,survivor_names,gene_bag):
    
    gene_bag["layer_1_2_cells_W1"] = []
    gene_bag["layer_1_2_cells_b1"] = []
    gene_bag["layer_2_2_cells_W2"] = []
    gene_bag["layer_2_2_cells_b2"] = []
    gene_bag["layer_3_2_cells_W3"] = []
    gene_bag["layer_3_2_cells_b3"] = []
    
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["W1"])),2):
            gene_bag["layer_1_2_cells_W1"].append(bugs[survivor_names[i]]["W1"][s:s+2,:])
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["b1"])),2):
            gene_bag["layer_1_2_cells_b1"].append(bugs[survivor_names[i]]["b1"][s:s+2,:])
            
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["W2"])),2):
            gene_bag["layer_2_2_cells_W2"].append(bugs[survivor_names[i]]["W2"][s:s+2,:])
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["b2"])),2):
            gene_bag["layer_2_2_cells_b2"].append(bugs[survivor_names[i]]["b2"][s:s+2,:])
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["decider_W3"])),2):
            gene_bag["layer_3_2_cells_W3"].append(bugs[survivor_names[i]]["decider_W3"][s:s+2,:])
    
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["decider_b3"])),2):
            gene_bag["layer_3_2_cells_b3"].append(bugs[survivor_names[i]]["decider_b3"][s:s+2,:])
            
            
    return gene_bag
        
    
def four_cell_shuffle(bugs,survivor_names,gene_bag):
    gene_bag["layer_1_4_cells_W1"] = []
    gene_bag["layer_1_4_cells_b1"] = []
    gene_bag["layer_2_4_cells_W2"] = []
    gene_bag["layer_2_4_cells_b2"] = []
    gene_bag["layer_3_4_cells_W3"] = []
    gene_bag["layer_3_4_cells_b3"] = []
    
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["W1"])),4):
            gene_bag["layer_1_4_cells_W1"].append(bugs[survivor_names[i]]["W1"][s:s+4,:])
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["b1"])),4):
            gene_bag["layer_1_4_cells_b1"].append(bugs[survivor_names[i]]["b1"][s:s+4,:])
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["W2"])),4):
            gene_bag["layer_2_4_cells_W2"].append(bugs[survivor_names[i]]["W2"][s:s+4,:])
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["b2"])),4):
            gene_bag["layer_2_4_cells_b2"].append(bugs[survivor_names[i]]["b2"][s:s+4,:])
            
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["decider_W3"])),4):
            gene_bag["layer_3_4_cells_W3"].append(bugs[survivor_names[i]]["decider_W3"][s:s+4,:])
            
            
    for i in range(len(survivor_names)):
        for s in range(0,int(len(bugs["bug0"]["decider_b3"])),4):
            gene_bag["layer_3_4_cells_b3"].append(bugs[survivor_names[i]]["decider_b3"][s:s+4,:])
            
            
    
    return gene_bag

def the_big_shuffler(bugs,survivor_names):
    gene_bag = {}
    
    gene_bag = single_cell_shuffle(bugs,survivor_names,gene_bag)
    
    gene_bag = two_cell_shuffle(bugs,survivor_names,gene_bag)
    
    gene_bag = four_cell_shuffle(bugs,survivor_names,gene_bag)
    
    return gene_bag


def single_cell_create(bugs,gene_bag):
    for i in range(0,len(bugs)//2):
        gene_W1 = []
        gene_b1 = []
        gene_W2 = []
        gene_b2 = []
        gene_W3 = []
        gene_b3 = []
        for k in range(len(bugs["bug0"]["W1"])):
            a = random.randint(0,len(gene_bag["layer_1_cells_W1"])-1)
            gene_W1.append(gene_bag["layer_1_cells_W1"][a])
             
            b = random.randint(0,len(gene_bag["layer_1_cells_b1"])-1)
            gene_b1.append(gene_bag["layer_1_cells_b1"][b])                
            
        for s in range(len(bugs["bug0"]["W2"])):
            c = random.randint(0,len(gene_bag["layer_2_cells_W2"])-1)
            gene_W2.append(gene_bag["layer_2_cells_W2"][c])
            
            d = random.randint(0,len(gene_bag["layer_2_cells_b2"])-1)
            gene_b2.append(gene_bag["layer_2_cells_b2"][d])
            
        for f in range(len(bugs["bug0"]["decider_W3"])):
            e = random.randint(0,len(gene_bag["layer_3_cells_W3"])-1)
            gene_W3.append(gene_bag["layer_3_cells_W3"][e])
            
            f = random.randint(0,len(gene_bag["layer_3_cells_b3"])-1)
            gene_b3.append(gene_bag["layer_3_cells_b3"][f])
                
        
        bugs["bug" + str(i)]["W1"] = np.vstack(gene_W1)
        bugs["bug" + str(i)]["b1"] = np.vstack(gene_b1)
        bugs["bug" + str(i)]["W2"] = np.vstack(gene_W2)
        bugs["bug" + str(i)]["b2"] = np.vstack(gene_b2)
        bugs["bug" + str(i)]["decider_W3"] = np.vstack(gene_W3)
        bugs["bug" + str(i)]["decider_b3"] = np.vstack(gene_b3)
        bugs["bug" + str(i)]["coordinates"] = np.ones((4,1))    
    return bugs



def  two_cell_create(bugs,gene_bag):
    for i in range(len(bugs) // 2,len(bugs) // 2 + (len(bugs) // 2 ) // 2):
        gene_W1 = []
        gene_b1 = []
        gene_W2 = []
        gene_b2 = []
        gene_W3 = []
        gene_b3 = []
        
        for k in range(len(bugs["bug0"]["W1"]) // 2):
            a = random.randint(0,len(gene_bag["layer_1_2_cells_W1"])-1)
            gene_W1.append(gene_bag["layer_1_2_cells_W1"][a])
                
            b = random.randint(0,len(gene_bag["layer_1_2_cells_b1"])-1)
            gene_b1.append(gene_bag["layer_1_2_cells_b1"][b])
            
        for s in range(len(bugs["bug0"]["W2"]) // 2):
        
            c = random.randint(0,len(gene_bag["layer_2_2_cells_W2"])-1)
            gene_W2.append(gene_bag["layer_2_2_cells_W2"][c])
            
            d = random.randint(0,len(gene_bag["layer_2_2_cells_b2"])-1)
            gene_b2.append(gene_bag["layer_2_2_cells_b2"][d])
            
        for j in range(0,len(bugs["bug0"]["decider_W3"]) // 2):
            e = random.randint(0,len(gene_bag["layer_3_2_cells_W3"])-1)
            gene_W3.append(gene_bag["layer_3_2_cells_W3"][e])
            
            f = random.randint(0,len(gene_bag["layer_3_2_cells_b3"])-1)
            gene_b3.append(gene_bag["layer_3_2_cells_b3"][f])
    
    
    
        bugs["bug" + str(i)]["W1"] = np.vstack(gene_W1)
        bugs["bug" + str(i)]["b1"] = np.vstack(gene_b1)
        bugs["bug" + str(i)]["W2"] = np.vstack(gene_W2)
        bugs["bug" + str(i)]["b2"] = np.vstack(gene_b2)
        #bugs["bug" + str(i)]["decider_W3"] = np.vstack(gene_W3)
        #bugs["bug" + str(i)]["decider_b3"] = np.vstack(gene_b3)
        bugs["bug" + str(i)]["coordinates"] = np.ones((4,1))
        
    return bugs
    
    
    
def four_cell_create(bugs,gene_bag):
        for i in range(len(bugs) // 2 + (len(bugs) // 2 ) // 2 , len(bugs) // 2 + (len(bugs) // 2 ) // 2 + (len(bugs) // 2) // 2):
            gene_W1 = []
            gene_b1 = []
            gene_W2 = []
            gene_b2 = []
            gene_W3 = []
            gene_b3 = []
            
            
            for k in range(len(bugs["bug0"]["W1"]) // 4):
                a = random.randint(0,len(gene_bag["layer_1_4_cells_W1"])-1)
                gene_W1.append(gene_bag["layer_1_4_cells_W1"][a])
                
                b = random.randint(0,len(gene_bag["layer_1_4_cells_b1"])-1)
                gene_b1.append(gene_bag["layer_1_4_cells_b1"][b])
            
            for s in range(len(bugs["bug0"]["W2"]) // 4):
        
                c = random.randint(0,len(gene_bag["layer_2_4_cells_W2"])-1)
                gene_W2.append(gene_bag["layer_2_4_cells_W2"][c])
            
                d = random.randint(0,len(gene_bag["layer_2_4_cells_b2"])-1)
                gene_b2.append(gene_bag["layer_2_4_cells_b2"][d])
            
            for j in range(0,len(bugs["bug0"]["decider_W3"]) // 4):
                e = random.randint(0,len(gene_bag["layer_3_4_cells_W3"])-1)
                gene_W3.append(gene_bag["layer_3_4_cells_W3"][e])
            
                f = random.randint(0,len(gene_bag["layer_3_4_cells_b3"])-1)
                gene_b3.append(gene_bag["layer_3_4_cells_b3"][f])
            
            
            
            bugs["bug" + str(i)]["W1"] = np.vstack(gene_W1)
            bugs["bug" + str(i)]["b1"] = np.vstack(gene_b1)
            bugs["bug" + str(i)]["W2"] = np.vstack(gene_W2)
            bugs["bug" + str(i)]["b2"] = np.vstack(gene_b2)
            #bugs["bug" + str(i)]["decider_W3"] = np.vstack(gene_W3)
            #bugs["bug" + str(i)]["decider_b3"] = np.vstack(gene_b3)
            bugs["bug" + str(i)]["coordinates"] = np.ones((4,1))
            
        return bugs
        
def start_show(bugs,food,iteration_number):
    for i in range(0,iteration_number + 1):
        
        movement_points = all_the_bugs_deciding(bugs,food)
        #print(movement_points)


        #print("beginning: " ,bugs["bug0"]["coordinates"])
        move_all_the_bugs(bugs,movement_points)
        #print("last: " ,bugs["bug0"]["coordinates"])
        #print("movement:" ,movement_points["bug0"])

        evaluating_bugs(bugs,food)

        survivor_names = natural_selection(bugs,food)
        print(survivor_names)
       
        if i < iteration_number:
            gene_bag = the_big_shuffler(bugs,survivor_names)
        #print(gene_bag)

            bugs = single_cell_create(bugs,gene_bag)

            bugs = two_cell_create(bugs,gene_bag)

            bugs = four_cell_create(bugs,gene_bag)

    return bugs,survivor_names
    
    
#This function will assemble bugs from scracth. It will randomly choose bugs intellect parts and unite them in a unique intellect.



    

In [94]:
food = make_food(10)
data_length =food["fo0"].shape[0] + 4 #(This 4 is symbolizes the four direction of movement)
num_data = len(food)

bugs = make_bugs(1,2400,8,data_length,num_data)
#print(bugs["bug0"])
bugs,survivor_names = start_show(bugs,food,100)
#print(bugs["bug0"])
print(survivor_names)

['bug824', 'bug1405', 'bug1572', 'bug1016', 'bug1689', 'bug1864', 'bug1757', 'bug1077', 'bug2140', 'bug279', 'bug183', 'bug1192', 'bug338', 'bug177', 'bug293', 'bug1111', 'bug1049', 'bug1218', 'bug2180', 'bug556', 'bug1332', 'bug1038', 'bug1090', 'bug1491', 'bug1320', 'bug576', 'bug1294', 'bug2370', 'bug431', 'bug705', 'bug13', 'bug2399', 'bug1173', 'bug834', 'bug304', 'bug2117', 'bug735', 'bug1705', 'bug1797', 'bug1411', 'bug842', 'bug1477', 'bug631', 'bug1215', 'bug317', 'bug502', 'bug1839', 'bug240', 'bug19', 'bug744', 'bug2146', 'bug577', 'bug2238', 'bug1475', 'bug1321', 'bug17', 'bug1549', 'bug998', 'bug1794', 'bug1440', 'bug2343', 'bug2042', 'bug1333', 'bug1790', 'bug372', 'bug825', 'bug1895', 'bug990', 'bug2341', 'bug1316', 'bug1782', 'bug753', 'bug1357', 'bug2190', 'bug574', 'bug1652', 'bug1318', 'bug854', 'bug765', 'bug1074', 'bug1831', 'bug1898', 'bug2366', 'bug353', 'bug2122', 'bug2011', 'bug737', 'bug1950', 'bug2162', 'bug776', 'bug1542', 'bug1656', 'bug1348', 'bug2193', 'b

['bug411', 'bug560', 'bug814', 'bug754', 'bug381', 'bug975', 'bug666', 'bug961', 'bug563', 'bug585', 'bug15', 'bug182', 'bug931', 'bug447', 'bug859', 'bug407', 'bug1434', 'bug270', 'bug367', 'bug1151', 'bug112', 'bug778', 'bug394', 'bug2399', 'bug1044', 'bug115', 'bug723', 'bug594', 'bug35', 'bug1025', 'bug148', 'bug328', 'bug113', 'bug185', 'bug932', 'bug1491', 'bug47', 'bug140', 'bug1088', 'bug326', 'bug830', 'bug1156', 'bug1244', 'bug1475', 'bug502', 'bug688', 'bug1572', 'bug575', 'bug402', 'bug810', 'bug350', 'bug581', 'bug1291', 'bug276', 'bug278', 'bug903', 'bug559', 'bug311', 'bug515', 'bug1019', 'bug1705', 'bug747', 'bug1789', 'bug482', 'bug541', 'bug537', 'bug681', 'bug55', 'bug840', 'bug427', 'bug1745', 'bug970', 'bug758', 'bug1045', 'bug497', 'bug302', 'bug1910', 'bug946', 'bug1797', 'bug39', 'bug925', 'bug608', 'bug387', 'bug912', 'bug1179', 'bug877', 'bug1508', 'bug213', 'bug2005', 'bug342', 'bug915', 'bug1149', 'bug766', 'bug555', 'bug294', 'bug146', 'bug1105', 'bug712', 

['bug913', 'bug923', 'bug1146', 'bug129', 'bug456', 'bug126', 'bug540', 'bug781', 'bug84', 'bug163', 'bug514', 'bug583', 'bug1135', 'bug175', 'bug1162', 'bug1088', 'bug857', 'bug231', 'bug2095', 'bug727', 'bug746', 'bug1155', 'bug809', 'bug82', 'bug998', 'bug589', 'bug1110', 'bug411', 'bug1137', 'bug370', 'bug1048', 'bug364', 'bug649', 'bug560', 'bug686', 'bug117', 'bug1149', 'bug827', 'bug674', 'bug54', 'bug1042', 'bug643', 'bug2093', 'bug158', 'bug132', 'bug1703', 'bug1014', 'bug791', 'bug1887', 'bug572', 'bug1034', 'bug1424', 'bug631', 'bug554', 'bug684', 'bug697', 'bug559', 'bug1236', 'bug2199', 'bug315', 'bug807', 'bug208', 'bug136', 'bug896', 'bug938', 'bug346', 'bug1027', 'bug212', 'bug828', 'bug1884', 'bug15', 'bug219', 'bug581', 'bug892', 'bug480', 'bug1013', 'bug264', 'bug1108', 'bug609', 'bug193', 'bug426', 'bug1120', 'bug420', 'bug8', 'bug207', 'bug823', 'bug106', 'bug1190', 'bug1032', 'bug217', 'bug1171', 'bug1350', 'bug1705', 'bug2317', 'bug1059', 'bug761', 'bug1053', 'bu

['bug518', 'bug1110', 'bug1114', 'bug2115', 'bug1009', 'bug1120', 'bug890', 'bug571', 'bug1294', 'bug288', 'bug722', 'bug1076', 'bug49', 'bug449', 'bug600', 'bug1175', 'bug287', 'bug783', 'bug619', 'bug426', 'bug506', 'bug1049', 'bug95', 'bug533', 'bug705', 'bug792', 'bug1119', 'bug372', 'bug391', 'bug827', 'bug1086', 'bug69', 'bug573', 'bug24', 'bug398', 'bug52', 'bug245', 'bug1132', 'bug931', 'bug393', 'bug158', 'bug1079', 'bug529', 'bug101', 'bug165', 'bug355', 'bug98', 'bug236', 'bug971', 'bug108', 'bug698', 'bug855', 'bug244', 'bug59', 'bug1034', 'bug538', 'bug491', 'bug1069', 'bug233', 'bug631', 'bug1168', 'bug2042', 'bug73', 'bug238', 'bug900', 'bug603', 'bug1043', 'bug444', 'bug790', 'bug1185', 'bug78', 'bug844', 'bug1029', 'bug423', 'bug421', 'bug892', 'bug66', 'bug984', 'bug540', 'bug729', 'bug1041', 'bug265', 'bug588', 'bug831', 'bug493', 'bug173', 'bug96', 'bug913', 'bug476', 'bug274', 'bug591', 'bug13', 'bug697', 'bug645', 'bug810', 'bug202', 'bug351', 'bug44', 'bug189', '

['bug822', 'bug415', 'bug157', 'bug582', 'bug889', 'bug413', 'bug68', 'bug46', 'bug895', 'bug580', 'bug1067', 'bug104', 'bug927', 'bug403', 'bug1155', 'bug1056', 'bug367', 'bug217', 'bug81', 'bug606', 'bug1058', 'bug74', 'bug1834', 'bug350', 'bug395', 'bug679', 'bug943', 'bug811', 'bug410', 'bug214', 'bug719', 'bug697', 'bug980', 'bug32', 'bug923', 'bug526', 'bug637', 'bug1594', 'bug1115', 'bug1077', 'bug746', 'bug862', 'bug294', 'bug806', 'bug1061', 'bug828', 'bug1162', 'bug795', 'bug944', 'bug500', 'bug55', 'bug1035', 'bug1132', 'bug733', 'bug14', 'bug1082', 'bug176', 'bug658', 'bug365', 'bug451', 'bug647', 'bug1074', 'bug940', 'bug507', 'bug932', 'bug460', 'bug465', 'bug525', 'bug1079', 'bug608', 'bug666', 'bug642', 'bug420', 'bug324', 'bug1065', 'bug482', 'bug910', 'bug387', 'bug1110', 'bug1116', 'bug1186', 'bug997', 'bug376', 'bug1101', 'bug218', 'bug314', 'bug2399', 'bug1003', 'bug1103', 'bug934', 'bug502', 'bug586', 'bug374', 'bug958', 'bug682', 'bug655', 'bug725', 'bug708', 'bu

['bug345', 'bug330', 'bug163', 'bug394', 'bug1151', 'bug255', 'bug1108', 'bug523', 'bug965', 'bug912', 'bug469', 'bug2168', 'bug267', 'bug792', 'bug536', 'bug975', 'bug249', 'bug793', 'bug1057', 'bug1011', 'bug806', 'bug386', 'bug315', 'bug205', 'bug845', 'bug1175', 'bug784', 'bug406', 'bug1192', 'bug625', 'bug64', 'bug538', 'bug1006', 'bug373', 'bug290', 'bug811', 'bug596', 'bug5', 'bug336', 'bug973', 'bug837', 'bug876', 'bug383', 'bug970', 'bug88', 'bug368', 'bug1051', 'bug921', 'bug437', 'bug207', 'bug312', 'bug471', 'bug1037', 'bug350', 'bug433', 'bug512', 'bug905', 'bug55', 'bug1086', 'bug149', 'bug467', 'bug54', 'bug1049', 'bug583', 'bug610', 'bug611', 'bug1024', 'bug139', 'bug998', 'bug789', 'bug962', 'bug174', 'bug59', 'bug1355', 'bug976', 'bug454', 'bug308', 'bug1045', 'bug1145', 'bug830', 'bug1637', 'bug907', 'bug296', 'bug902', 'bug333', 'bug980', 'bug800', 'bug715', 'bug977', 'bug677', 'bug1195', 'bug251', 'bug20', 'bug507', 'bug242', 'bug947', 'bug103', 'bug168', 'bug841',

['bug353', 'bug712', 'bug530', 'bug246', 'bug31', 'bug273', 'bug60', 'bug207', 'bug1153', 'bug796', 'bug363', 'bug1160', 'bug20', 'bug887', 'bug679', 'bug1597', 'bug346', 'bug800', 'bug571', 'bug968', 'bug348', 'bug1190', 'bug1058', 'bug784', 'bug239', 'bug1114', 'bug759', 'bug188', 'bug101', 'bug1880', 'bug1172', 'bug183', 'bug1121', 'bug108', 'bug1062', 'bug1553', 'bug375', 'bug622', 'bug67', 'bug847', 'bug44', 'bug489', 'bug458', 'bug258', 'bug296', 'bug173', 'bug49', 'bug66', 'bug985', 'bug472', 'bug460', 'bug535', 'bug213', 'bug913', 'bug1026', 'bug1144', 'bug837', 'bug933', 'bug705', 'bug803', 'bug859', 'bug362', 'bug367', 'bug366', 'bug409', 'bug413', 'bug885', 'bug609', 'bug1127', 'bug83', 'bug284', 'bug673', 'bug515', 'bug209', 'bug793', 'bug402', 'bug701', 'bug886', 'bug745', 'bug197', 'bug393', 'bug810', 'bug983', 'bug797', 'bug102', 'bug545', 'bug619', 'bug298', 'bug1030', 'bug861', 'bug1035', 'bug141', 'bug879', 'bug310', 'bug1038', 'bug69', 'bug105', 'bug1196', 'bug488', 

['bug1141', 'bug1152', 'bug196', 'bug2063', 'bug736', 'bug851', 'bug239', 'bug891', 'bug507', 'bug804', 'bug634', 'bug208', 'bug706', 'bug1181', 'bug1', 'bug751', 'bug757', 'bug893', 'bug570', 'bug168', 'bug532', 'bug955', 'bug977', 'bug493', 'bug342', 'bug167', 'bug665', 'bug1137', 'bug238', 'bug99', 'bug1099', 'bug453', 'bug195', 'bug808', 'bug874', 'bug1372', 'bug565', 'bug1199', 'bug415', 'bug760', 'bug456', 'bug772', 'bug987', 'bug872', 'bug668', 'bug765', 'bug1117', 'bug2086', 'bug755', 'bug943', 'bug771', 'bug1041', 'bug539', 'bug1088', 'bug303', 'bug793', 'bug126', 'bug870', 'bug785', 'bug853', 'bug624', 'bug621', 'bug769', 'bug685', 'bug1160', 'bug304', 'bug71', 'bug533', 'bug380', 'bug1031', 'bug1151', 'bug513', 'bug573', 'bug880', 'bug666', 'bug742', 'bug333', 'bug1348', 'bug1187', 'bug509', 'bug886', 'bug1072', 'bug404', 'bug1006', 'bug276', 'bug961', 'bug848', 'bug840', 'bug529', 'bug81', 'bug182', 'bug618', 'bug1019', 'bug29', 'bug890', 'bug1192', 'bug642', 'bug408', 'bug

['bug759', 'bug17', 'bug138', 'bug967', 'bug385', 'bug210', 'bug989', 'bug30', 'bug1044', 'bug1113', 'bug1176', 'bug928', 'bug673', 'bug599', 'bug418', 'bug365', 'bug736', 'bug457', 'bug844', 'bug986', 'bug330', 'bug251', 'bug261', 'bug309', 'bug436', 'bug147', 'bug910', 'bug550', 'bug999', 'bug269', 'bug364', 'bug1179', 'bug561', 'bug94', 'bug900', 'bug167', 'bug1', 'bug788', 'bug96', 'bug588', 'bug878', 'bug27', 'bug22', 'bug870', 'bug434', 'bug971', 'bug1797', 'bug422', 'bug1132', 'bug1060', 'bug641', 'bug794', 'bug919', 'bug137', 'bug899', 'bug1036', 'bug168', 'bug1007', 'bug570', 'bug1075', 'bug1114', 'bug737', 'bug527', 'bug218', 'bug223', 'bug525', 'bug501', 'bug949', 'bug1235', 'bug474', 'bug1026', 'bug688', 'bug912', 'bug739', 'bug1034', 'bug28', 'bug271', 'bug943', 'bug143', 'bug735', 'bug680', 'bug132', 'bug681', 'bug732', 'bug598', 'bug243', 'bug806', 'bug327', 'bug101', 'bug961', 'bug378', 'bug807', 'bug615', 'bug41', 'bug1161', 'bug6', 'bug1073', 'bug1035', 'bug242', 'bug

['bug42', 'bug100', 'bug228', 'bug779', 'bug508', 'bug216', 'bug942', 'bug1797', 'bug887', 'bug1086', 'bug343', 'bug376', 'bug1163', 'bug444', 'bug174', 'bug263', 'bug793', 'bug203', 'bug367', 'bug472', 'bug1117', 'bug765', 'bug1320', 'bug370', 'bug165', 'bug521', 'bug134', 'bug667', 'bug829', 'bug495', 'bug849', 'bug297', 'bug562', 'bug1079', 'bug850', 'bug1773', 'bug427', 'bug978', 'bug658', 'bug1023', 'bug516', 'bug1111', 'bug965', 'bug154', 'bug249', 'bug125', 'bug795', 'bug1140', 'bug767', 'bug2005', 'bug312', 'bug606', 'bug1197', 'bug1069', 'bug649', 'bug666', 'bug84', 'bug414', 'bug530', 'bug90', 'bug1189', 'bug883', 'bug386', 'bug2042', 'bug540', 'bug436', 'bug382', 'bug955', 'bug580', 'bug257', 'bug885', 'bug684', 'bug906', 'bug1038', 'bug585', 'bug996', 'bug786', 'bug1508', 'bug523', 'bug615', 'bug244', 'bug699', 'bug150', 'bug191', 'bug284', 'bug888', 'bug1139', 'bug303', 'bug86', 'bug846', 'bug838', 'bug821', 'bug126', 'bug420', 'bug714', 'bug1136', 'bug689', 'bug946', 'bug

['bug689', 'bug271', 'bug948', 'bug225', 'bug762', 'bug749', 'bug218', 'bug111', 'bug442', 'bug30', 'bug353', 'bug857', 'bug613', 'bug172', 'bug420', 'bug1096', 'bug16', 'bug152', 'bug238', 'bug610', 'bug1357', 'bug769', 'bug13', 'bug233', 'bug226', 'bug318', 'bug1870', 'bug562', 'bug1095', 'bug119', 'bug285', 'bug606', 'bug741', 'bug721', 'bug278', 'bug41', 'bug637', 'bug804', 'bug1142', 'bug887', 'bug1171', 'bug732', 'bug400', 'bug465', 'bug62', 'bug320', 'bug543', 'bug182', 'bug575', 'bug1076', 'bug454', 'bug382', 'bug798', 'bug557', 'bug994', 'bug960', 'bug728', 'bug208', 'bug532', 'bug751', 'bug191', 'bug991', 'bug560', 'bug315', 'bug1035', 'bug307', 'bug1972', 'bug881', 'bug1077', 'bug837', 'bug766', 'bug707', 'bug687', 'bug441', 'bug355', 'bug449', 'bug538', 'bug785', 'bug913', 'bug398', 'bug366', 'bug1060', 'bug2139', 'bug933', 'bug1834', 'bug665', 'bug950', 'bug641', 'bug1121', 'bug2092', 'bug554', 'bug684', 'bug605', 'bug10', 'bug845', 'bug635', 'bug339', 'bug1163', 'bug2221'

['bug860', 'bug615', 'bug853', 'bug651', 'bug522', 'bug903', 'bug367', 'bug1191', 'bug77', 'bug1165', 'bug207', 'bug2092', 'bug962', 'bug97', 'bug2', 'bug167', 'bug679', 'bug569', 'bug629', 'bug74', 'bug376', 'bug45', 'bug61', 'bug703', 'bug1181', 'bug2050', 'bug872', 'bug387', 'bug593', 'bug151', 'bug351', 'bug826', 'bug381', 'bug516', 'bug40', 'bug836', 'bug987', 'bug550', 'bug296', 'bug1105', 'bug346', 'bug168', 'bug1127', 'bug778', 'bug7', 'bug256', 'bug9', 'bug572', 'bug499', 'bug78', 'bug1164', 'bug958', 'bug876', 'bug137', 'bug1070', 'bug1220', 'bug177', 'bug1048', 'bug1085', 'bug402', 'bug43', 'bug216', 'bug509', 'bug1805', 'bug1045', 'bug758', 'bug888', 'bug968', 'bug248', 'bug56', 'bug86', 'bug988', 'bug1109', 'bug278', 'bug712', 'bug931', 'bug607', 'bug188', 'bug73', 'bug801', 'bug669', 'bug764', 'bug373', 'bug104', 'bug456', 'bug773', 'bug828', 'bug1030', 'bug697', 'bug841', 'bug287', 'bug751', 'bug348', 'bug323', 'bug32', 'bug1161', 'bug871', 'bug1113', 'bug365', 'bug997',

['bug366', 'bug823', 'bug477', 'bug469', 'bug480', 'bug932', 'bug991', 'bug1080', 'bug128', 'bug491', 'bug593', 'bug599', 'bug856', 'bug560', 'bug376', 'bug1110', 'bug413', 'bug550', 'bug198', 'bug830', 'bug73', 'bug982', 'bug377', 'bug239', 'bug1008', 'bug1076', 'bug1044', 'bug620', 'bug935', 'bug266', 'bug530', 'bug1237', 'bug799', 'bug336', 'bug1980', 'bug1313', 'bug379', 'bug574', 'bug605', 'bug942', 'bug501', 'bug608', 'bug1155', 'bug410', 'bug383', 'bug855', 'bug1019', 'bug240', 'bug956', 'bug632', 'bug1000', 'bug52', 'bug801', 'bug335', 'bug590', 'bug927', 'bug812', 'bug199', 'bug7', 'bug20', 'bug553', 'bug872', 'bug402', 'bug132', 'bug979', 'bug953', 'bug1149', 'bug973', 'bug23', 'bug32', 'bug180', 'bug849', 'bug11', 'bug22', 'bug853', 'bug742', 'bug110', 'bug717', 'bug150', 'bug955', 'bug1043', 'bug97', 'bug992', 'bug384', 'bug478', 'bug694', 'bug219', 'bug700', 'bug24', 'bug261', 'bug42', 'bug1168', 'bug1022', 'bug514', 'bug923', 'bug668', 'bug987', 'bug223', 'bug346', 'bug20

['bug1047', 'bug534', 'bug877', 'bug647', 'bug747', 'bug674', 'bug142', 'bug419', 'bug1167', 'bug740', 'bug742', 'bug829', 'bug600', 'bug689', 'bug890', 'bug945', 'bug1075', 'bug976', 'bug927', 'bug979', 'bug145', 'bug755', 'bug327', 'bug1091', 'bug458', 'bug499', 'bug849', 'bug103', 'bug174', 'bug822', 'bug508', 'bug585', 'bug854', 'bug1080', 'bug703', 'bug844', 'bug254', 'bug453', 'bug413', 'bug920', 'bug243', 'bug425', 'bug692', 'bug1182', 'bug965', 'bug633', 'bug522', 'bug868', 'bug64', 'bug895', 'bug140', 'bug1124', 'bug561', 'bug532', 'bug752', 'bug955', 'bug195', 'bug873', 'bug548', 'bug172', 'bug1029', 'bug1185', 'bug1158', 'bug116', 'bug262', 'bug71', 'bug1100', 'bug590', 'bug298', 'bug1076', 'bug211', 'bug1191', 'bug1160', 'bug77', 'bug736', 'bug286', 'bug1171', 'bug878', 'bug469', 'bug617', 'bug249', 'bug584', 'bug236', 'bug758', 'bug654', 'bug1001', 'bug639', 'bug8', 'bug344', 'bug900', 'bug80', 'bug296', 'bug1078', 'bug907', 'bug1086', 'bug462', 'bug658', 'bug252', 'bug989

['bug30', 'bug954', 'bug871', 'bug526', 'bug581', 'bug883', 'bug674', 'bug615', 'bug911', 'bug624', 'bug1066', 'bug132', 'bug475', 'bug198', 'bug907', 'bug628', 'bug726', 'bug311', 'bug844', 'bug1140', 'bug76', 'bug587', 'bug890', 'bug391', 'bug675', 'bug286', 'bug344', 'bug1023', 'bug644', 'bug405', 'bug547', 'bug125', 'bug394', 'bug220', 'bug200', 'bug446', 'bug724', 'bug20', 'bug775', 'bug388', 'bug180', 'bug648', 'bug22', 'bug501', 'bug402', 'bug863', 'bug927', 'bug669', 'bug1166', 'bug387', 'bug564', 'bug54', 'bug670', 'bug427', 'bug93', 'bug380', 'bug631', 'bug923', 'bug381', 'bug319', 'bug350', 'bug656', 'bug108', 'bug274', 'bug50', 'bug264', 'bug202', 'bug1168', 'bug415', 'bug795', 'bug1079', 'bug43', 'bug1100', 'bug261', 'bug1082', 'bug1008', 'bug243', 'bug620', 'bug163', 'bug45', 'bug840', 'bug985', 'bug333', 'bug1174', 'bug998', 'bug290', 'bug70', 'bug498', 'bug994', 'bug1118', 'bug278', 'bug508', 'bug481', 'bug997', 'bug807', 'bug143', 'bug492', 'bug530', 'bug443', 'bug1062

['bug531', 'bug540', 'bug751', 'bug715', 'bug716', 'bug890', 'bug258', 'bug985', 'bug803', 'bug326', 'bug504', 'bug825', 'bug339', 'bug898', 'bug201', 'bug355', 'bug282', 'bug1031', 'bug709', 'bug214', 'bug19', 'bug175', 'bug1003', 'bug251', 'bug727', 'bug310', 'bug913', 'bug1191', 'bug1044', 'bug169', 'bug458', 'bug965', 'bug418', 'bug526', 'bug393', 'bug1125', 'bug1149', 'bug1047', 'bug217', 'bug192', 'bug1043', 'bug221', 'bug22', 'bug768', 'bug712', 'bug864', 'bug830', 'bug1178', 'bug145', 'bug684', 'bug532', 'bug1060', 'bug466', 'bug1094', 'bug735', 'bug552', 'bug683', 'bug638', 'bug810', 'bug563', 'bug610', 'bug451', 'bug390', 'bug132', 'bug306', 'bug775', 'bug697', 'bug905', 'bug957', 'bug210', 'bug646', 'bug797', 'bug613', 'bug714', 'bug265', 'bug455', 'bug902', 'bug755', 'bug533', 'bug408', 'bug1035', 'bug2', 'bug71', 'bug918', 'bug229', 'bug429', 'bug500', 'bug682', 'bug717', 'bug1077', 'bug740', 'bug934', 'bug111', 'bug290', 'bug55', 'bug5', 'bug524', 'bug813', 'bug950', 'bug

['bug944', 'bug666', 'bug678', 'bug478', 'bug629', 'bug724', 'bug578', 'bug627', 'bug219', 'bug1151', 'bug977', 'bug392', 'bug409', 'bug378', 'bug784', 'bug472', 'bug1192', 'bug127', 'bug603', 'bug807', 'bug895', 'bug904', 'bug419', 'bug399', 'bug322', 'bug260', 'bug1088', 'bug38', 'bug19', 'bug939', 'bug1146', 'bug873', 'bug1147', 'bug291', 'bug1009', 'bug5', 'bug348', 'bug462', 'bug744', 'bug341', 'bug232', 'bug148', 'bug790', 'bug312', 'bug762', 'bug916', 'bug1183', 'bug925', 'bug717', 'bug259', 'bug452', 'bug1179', 'bug741', 'bug405', 'bug596', 'bug1131', 'bug52', 'bug1122', 'bug872', 'bug230', 'bug748', 'bug493', 'bug516', 'bug858', 'bug1002', 'bug738', 'bug1108', 'bug159', 'bug371', 'bug17', 'bug198', 'bug240', 'bug410', 'bug953', 'bug732', 'bug735', 'bug1167', 'bug1199', 'bug450', 'bug864', 'bug868', 'bug994', 'bug201', 'bug974', 'bug651', 'bug1082', 'bug573', 'bug648', 'bug698', 'bug893', 'bug900', 'bug131', 'bug295', 'bug460', 'bug29', 'bug204', 'bug255', 'bug1168', 'bug503', 

['bug1', 'bug432', 'bug815', 'bug947', 'bug0', 'bug545', 'bug502', 'bug555', 'bug1004', 'bug790', 'bug814', 'bug675', 'bug817', 'bug1054', 'bug1106', 'bug929', 'bug882', 'bug400', 'bug984', 'bug863', 'bug625', 'bug278', 'bug638', 'bug996', 'bug424', 'bug110', 'bug231', 'bug820', 'bug686', 'bug795', 'bug536', 'bug506', 'bug25', 'bug774', 'bug1061', 'bug37', 'bug783', 'bug523', 'bug806', 'bug988', 'bug848', 'bug1022', 'bug265', 'bug365', 'bug236', 'bug460', 'bug1112', 'bug168', 'bug4', 'bug1060', 'bug614', 'bug933', 'bug196', 'bug1177', 'bug802', 'bug893', 'bug1011', 'bug239', 'bug272', 'bug463', 'bug95', 'bug870', 'bug964', 'bug423', 'bug494', 'bug45', 'bug998', 'bug57', 'bug922', 'bug1190', 'bug194', 'bug477', 'bug503', 'bug212', 'bug1095', 'bug363', 'bug875', 'bug293', 'bug649', 'bug652', 'bug109', 'bug770', 'bug444', 'bug548', 'bug1048', 'bug1085', 'bug304', 'bug631', 'bug256', 'bug1098', 'bug573', 'bug1074', 'bug93', 'bug1044', 'bug15', 'bug1070', 'bug426', 'bug327', 'bug834', 'bug1

['bug572', 'bug1123', 'bug345', 'bug791', 'bug275', 'bug253', 'bug900', 'bug1164', 'bug601', 'bug732', 'bug825', 'bug1094', 'bug1185', 'bug822', 'bug123', 'bug301', 'bug294', 'bug1025', 'bug884', 'bug322', 'bug543', 'bug762', 'bug102', 'bug618', 'bug357', 'bug1176', 'bug420', 'bug131', 'bug1006', 'bug129', 'bug843', 'bug907', 'bug602', 'bug650', 'bug724', 'bug647', 'bug797', 'bug990', 'bug134', 'bug1127', 'bug452', 'bug702', 'bug476', 'bug983', 'bug342', 'bug816', 'bug188', 'bug581', 'bug1061', 'bug806', 'bug897', 'bug957', 'bug34', 'bug142', 'bug1005', 'bug181', 'bug904', 'bug1099', 'bug532', 'bug88', 'bug510', 'bug823', 'bug490', 'bug527', 'bug472', 'bug763', 'bug503', 'bug414', 'bug457', 'bug723', 'bug817', 'bug307', 'bug755', 'bug982', 'bug391', 'bug277', 'bug539', 'bug313', 'bug150', 'bug485', 'bug261', 'bug285', 'bug137', 'bug1073', 'bug281', 'bug553', 'bug799', 'bug882', 'bug315', 'bug1141', 'bug865', 'bug413', 'bug182', 'bug207', 'bug1007', 'bug915', 'bug1126', 'bug395', 'bug64

['bug732', 'bug842', 'bug882', 'bug774', 'bug629', 'bug445', 'bug1042', 'bug714', 'bug599', 'bug62', 'bug85', 'bug1178', 'bug351', 'bug129', 'bug54', 'bug526', 'bug862', 'bug299', 'bug262', 'bug610', 'bug197', 'bug743', 'bug256', 'bug1074', 'bug564', 'bug968', 'bug172', 'bug911', 'bug518', 'bug645', 'bug1173', 'bug461', 'bug278', 'bug615', 'bug860', 'bug1166', 'bug784', 'bug273', 'bug1198', 'bug140', 'bug4', 'bug1010', 'bug73', 'bug568', 'bug383', 'bug641', 'bug898', 'bug201', 'bug71', 'bug689', 'bug881', 'bug86', 'bug430', 'bug104', 'bug950', 'bug1005', 'bug324', 'bug142', 'bug504', 'bug382', 'bug120', 'bug240', 'bug395', 'bug215', 'bug481', 'bug177', 'bug439', 'bug685', 'bug37', 'bug43', 'bug1007', 'bug1117', 'bug195', 'bug926', 'bug620', 'bug248', 'bug691', 'bug241', 'bug895', 'bug402', 'bug347', 'bug3', 'bug1008', 'bug1140', 'bug1049', 'bug98', 'bug901', 'bug335', 'bug1030', 'bug1124', 'bug936', 'bug185', 'bug341', 'bug652', 'bug822', 'bug728', 'bug781', 'bug454', 'bug813', 'bug856

['bug1199', 'bug1152', 'bug531', 'bug34', 'bug553', 'bug1149', 'bug325', 'bug958', 'bug126', 'bug185', 'bug941', 'bug615', 'bug438', 'bug215', 'bug1139', 'bug834', 'bug403', 'bug1175', 'bug526', 'bug494', 'bug606', 'bug724', 'bug905', 'bug892', 'bug550', 'bug1083', 'bug35', 'bug479', 'bug621', 'bug901', 'bug897', 'bug656', 'bug1174', 'bug470', 'bug532', 'bug384', 'bug23', 'bug851', 'bug300', 'bug399', 'bug342', 'bug297', 'bug638', 'bug273', 'bug1079', 'bug109', 'bug1171', 'bug223', 'bug635', 'bug1023', 'bug218', 'bug379', 'bug979', 'bug611', 'bug576', 'bug38', 'bug795', 'bug637', 'bug605', 'bug753', 'bug907', 'bug723', 'bug786', 'bug392', 'bug909', 'bug424', 'bug1176', 'bug865', 'bug473', 'bug26', 'bug1172', 'bug518', 'bug289', 'bug369', 'bug410', 'bug458', 'bug280', 'bug382', 'bug985', 'bug147', 'bug78', 'bug125', 'bug528', 'bug146', 'bug920', 'bug1', 'bug243', 'bug1072', 'bug1046', 'bug955', 'bug450', 'bug1187', 'bug976', 'bug1151', 'bug244', 'bug525', 'bug557', 'bug541', 'bug757', '

['bug747', 'bug172', 'bug58', 'bug1939', 'bug701', 'bug377', 'bug753', 'bug1023', 'bug1038', 'bug1046', 'bug112', 'bug500', 'bug799', 'bug776', 'bug393', 'bug221', 'bug833', 'bug367', 'bug435', 'bug455', 'bug752', 'bug1111', 'bug849', 'bug16', 'bug401', 'bug322', 'bug797', 'bug400', 'bug334', 'bug1315', 'bug814', 'bug411', 'bug631', 'bug615', 'bug1175', 'bug800', 'bug537', 'bug1113', 'bug567', 'bug105', 'bug458', 'bug48', 'bug479', 'bug807', 'bug158', 'bug1019', 'bug617', 'bug794', 'bug532', 'bug854', 'bug42', 'bug898', 'bug453', 'bug738', 'bug476', 'bug627', 'bug504', 'bug1061', 'bug783', 'bug975', 'bug397', 'bug140', 'bug484', 'bug791', 'bug449', 'bug242', 'bug192', 'bug22', 'bug282', 'bug409', 'bug480', 'bug649', 'bug385', 'bug102', 'bug1168', 'bug639', 'bug950', 'bug77', 'bug95', 'bug1000', 'bug594', 'bug744', 'bug283', 'bug553', 'bug1172', 'bug121', 'bug586', 'bug171', 'bug1076', 'bug338', 'bug507', 'bug196', 'bug481', 'bug717', 'bug1011', 'bug388', 'bug1141', 'bug861', 'bug239', 

['bug283', 'bug1160', 'bug1083', 'bug563', 'bug918', 'bug586', 'bug684', 'bug436', 'bug659', 'bug458', 'bug585', 'bug171', 'bug1098', 'bug327', 'bug202', 'bug231', 'bug981', 'bug505', 'bug160', 'bug509', 'bug760', 'bug797', 'bug134', 'bug859', 'bug938', 'bug78', 'bug75', 'bug1095', 'bug255', 'bug208', 'bug698', 'bug560', 'bug475', 'bug655', 'bug1056', 'bug879', 'bug116', 'bug754', 'bug665', 'bug1046', 'bug168', 'bug1134', 'bug1178', 'bug496', 'bug162', 'bug191', 'bug1192', 'bug364', 'bug803', 'bug214', 'bug1050', 'bug657', 'bug649', 'bug1016', 'bug506', 'bug31', 'bug343', 'bug142', 'bug805', 'bug996', 'bug796', 'bug26', 'bug163', 'bug379', 'bug288', 'bug143', 'bug102', 'bug135', 'bug99', 'bug264', 'bug913', 'bug802', 'bug375', 'bug1135', 'bug2351', 'bug764', 'bug921', 'bug261', 'bug369', 'bug729', 'bug472', 'bug559', 'bug855', 'bug845', 'bug367', 'bug1132', 'bug799', 'bug1191', 'bug765', 'bug652', 'bug583', 'bug27', 'bug493', 'bug632', 'bug453', 'bug1080', 'bug474', 'bug424', 'bug1184'

['bug350', 'bug593', 'bug880', 'bug866', 'bug1073', 'bug482', 'bug784', 'bug519', 'bug124', 'bug58', 'bug1080', 'bug542', 'bug381', 'bug299', 'bug1041', 'bug346', 'bug572', 'bug822', 'bug434', 'bug195', 'bug464', 'bug510', 'bug728', 'bug1011', 'bug986', 'bug106', 'bug850', 'bug667', 'bug441', 'bug12', 'bug600', 'bug913', 'bug1118', 'bug897', 'bug546', 'bug387', 'bug522', 'bug1086', 'bug967', 'bug846', 'bug579', 'bug718', 'bug896', 'bug762', 'bug292', 'bug401', 'bug210', 'bug928', 'bug48', 'bug148', 'bug811', 'bug1008', 'bug1053', 'bug671', 'bug120', 'bug502', 'bug802', 'bug91', 'bug319', 'bug1076', 'bug1180', 'bug663', 'bug806', 'bug1153', 'bug268', 'bug1030', 'bug907', 'bug1195', 'bug1072', 'bug413', 'bug909', 'bug1186', 'bug571', 'bug248', 'bug877', 'bug830', 'bug295', 'bug1061', 'bug1019', 'bug162', 'bug274', 'bug1179', 'bug679', 'bug757', 'bug868', 'bug937', 'bug958', 'bug1131', 'bug1126', 'bug285', 'bug207', 'bug834', 'bug933', 'bug1089', 'bug892', 'bug634', 'bug455', 'bug615', 'b

['bug2095', 'bug234', 'bug938', 'bug483', 'bug816', 'bug591', 'bug781', 'bug957', 'bug790', 'bug477', 'bug787', 'bug197', 'bug966', 'bug472', 'bug952', 'bug799', 'bug847', 'bug842', 'bug291', 'bug1139', 'bug836', 'bug462', 'bug886', 'bug600', 'bug191', 'bug442', 'bug40', 'bug1009', 'bug811', 'bug569', 'bug960', 'bug1022', 'bug403', 'bug22', 'bug328', 'bug473', 'bug1084', 'bug413', 'bug562', 'bug46', 'bug984', 'bug866', 'bug823', 'bug805', 'bug1145', 'bug279', 'bug131', 'bug581', 'bug557', 'bug373', 'bug317', 'bug432', 'bug96', 'bug943', 'bug559', 'bug134', 'bug111', 'bug896', 'bug724', 'bug495', 'bug891', 'bug712', 'bug1148', 'bug300', 'bug637', 'bug959', 'bug939', 'bug215', 'bug1028', 'bug1153', 'bug840', 'bug918', 'bug160', 'bug1177', 'bug1063', 'bug102', 'bug639', 'bug875', 'bug1142', 'bug975', 'bug289', 'bug404', 'bug299', 'bug286', 'bug872', 'bug625', 'bug674', 'bug1042', 'bug345', 'bug169', 'bug644', 'bug874', 'bug611', 'bug479', 'bug1098', 'bug693', 'bug120', 'bug1133', 'bug508'

['bug762', 'bug1135', 'bug767', 'bug1220', 'bug850', 'bug836', 'bug53', 'bug487', 'bug384', 'bug555', 'bug991', 'bug694', 'bug1112', 'bug1115', 'bug1023', 'bug629', 'bug375', 'bug710', 'bug1009', 'bug420', 'bug447', 'bug795', 'bug1187', 'bug1191', 'bug282', 'bug364', 'bug129', 'bug120', 'bug52', 'bug780', 'bug367', 'bug966', 'bug138', 'bug371', 'bug632', 'bug391', 'bug738', 'bug435', 'bug233', 'bug281', 'bug1087', 'bug779', 'bug960', 'bug1042', 'bug89', 'bug1146', 'bug30', 'bug309', 'bug377', 'bug363', 'bug672', 'bug429', 'bug24', 'bug1157', 'bug912', 'bug61', 'bug772', 'bug1047', 'bug434', 'bug521', 'bug804', 'bug1102', 'bug1050', 'bug1158', 'bug338', 'bug797', 'bug1092', 'bug937', 'bug894', 'bug907', 'bug677', 'bug639', 'bug421', 'bug140', 'bug171', 'bug614', 'bug624', 'bug500', 'bug160', 'bug352', 'bug295', 'bug860', 'bug869', 'bug728', 'bug1166', 'bug107', 'bug914', 'bug96', 'bug1190', 'bug973', 'bug1067', 'bug1197', 'bug489', 'bug858', 'bug379', 'bug771', 'bug161', 'bug748', 'bug1

['bug825', 'bug513', 'bug457', 'bug952', 'bug461', 'bug1094', 'bug619', 'bug1170', 'bug733', 'bug932', 'bug822', 'bug935', 'bug518', 'bug865', 'bug144', 'bug557', 'bug868', 'bug914', 'bug366', 'bug540', 'bug1055', 'bug1010', 'bug348', 'bug762', 'bug632', 'bug306', 'bug329', 'bug51', 'bug200', 'bug66', 'bug1127', 'bug1034', 'bug852', 'bug983', 'bug37', 'bug791', 'bug754', 'bug618', 'bug498', 'bug844', 'bug675', 'bug227', 'bug371', 'bug446', 'bug464', 'bug1000', 'bug530', 'bug98', 'bug715', 'bug817', 'bug394', 'bug434', 'bug137', 'bug323', 'bug875', 'bug551', 'bug190', 'bug1188', 'bug352', 'bug857', 'bug1054', 'bug1046', 'bug853', 'bug992', 'bug331', 'bug773', 'bug548', 'bug287', 'bug926', 'bug96', 'bug25', 'bug954', 'bug436', 'bug453', 'bug927', 'bug635', 'bug962', 'bug1093', 'bug719', 'bug863', 'bug718', 'bug829', 'bug930', 'bug770', 'bug949', 'bug631', 'bug83', 'bug330', 'bug899', 'bug405', 'bug1001', 'bug273', 'bug404', 'bug310', 'bug408', 'bug400', 'bug316', 'bug458', 'bug779', 'bug

['bug61', 'bug1031', 'bug660', 'bug869', 'bug1009', 'bug1085', 'bug611', 'bug838', 'bug1010', 'bug249', 'bug584', 'bug199', 'bug73', 'bug534', 'bug757', 'bug1013', 'bug867', 'bug956', 'bug557', 'bug844', 'bug1134', 'bug965', 'bug1141', 'bug183', 'bug632', 'bug117', 'bug760', 'bug363', 'bug601', 'bug487', 'bug1078', 'bug1046', 'bug1152', 'bug724', 'bug347', 'bug373', 'bug759', 'bug571', 'bug241', 'bug951', 'bug589', 'bug942', 'bug709', 'bug1079', 'bug1167', 'bug1146', 'bug831', 'bug684', 'bug550', 'bug187', 'bug420', 'bug3', 'bug45', 'bug941', 'bug885', 'bug720', 'bug774', 'bug441', 'bug286', 'bug175', 'bug165', 'bug1124', 'bug28', 'bug334', 'bug159', 'bug973', 'bug713', 'bug871', 'bug20', 'bug455', 'bug1137', 'bug1072', 'bug145', 'bug763', 'bug179', 'bug661', 'bug1047', 'bug1140', 'bug348', 'bug302', 'bug880', 'bug805', 'bug1132', 'bug758', 'bug22', 'bug106', 'bug92', 'bug337', 'bug88', 'bug1106', 'bug170', 'bug675', 'bug133', 'bug346', 'bug398', 'bug680', 'bug677', 'bug872', 'bug980',

['bug233', 'bug790', 'bug1109', 'bug776', 'bug1063', 'bug449', 'bug666', 'bug957', 'bug454', 'bug655', 'bug571', 'bug110', 'bug777', 'bug434', 'bug647', 'bug221', 'bug491', 'bug892', 'bug913', 'bug1124', 'bug12', 'bug763', 'bug96', 'bug784', 'bug875', 'bug772', 'bug980', 'bug533', 'bug1141', 'bug163', 'bug419', 'bug745', 'bug839', 'bug607', 'bug489', 'bug785', 'bug29', 'bug410', 'bug369', 'bug912', 'bug452', 'bug310', 'bug1052', 'bug683', 'bug57', 'bug600', 'bug328', 'bug1028', 'bug563', 'bug480', 'bug513', 'bug1105', 'bug354', 'bug920', 'bug1035', 'bug868', 'bug19', 'bug979', 'bug986', 'bug485', 'bug646', 'bug183', 'bug1199', 'bug311', 'bug843', 'bug902', 'bug955', 'bug261', 'bug417', 'bug644', 'bug547', 'bug189', 'bug200', 'bug945', 'bug26', 'bug1051', 'bug382', 'bug365', 'bug591', 'bug443', 'bug833', 'bug988', 'bug542', 'bug874', 'bug549', 'bug759', 'bug1179', 'bug31', 'bug1026', 'bug143', 'bug97', 'bug811', 'bug742', 'bug51', 'bug854', 'bug105', 'bug1044', 'bug858', 'bug928', 'bug7

['bug1031', 'bug858', 'bug635', 'bug647', 'bug1049', 'bug619', 'bug156', 'bug462', 'bug571', 'bug961', 'bug905', 'bug1117', 'bug442', 'bug703', 'bug986', 'bug336', 'bug674', 'bug272', 'bug255', 'bug724', 'bug1007', 'bug251', 'bug938', 'bug428', 'bug552', 'bug872', 'bug915', 'bug1510', 'bug1199', 'bug443', 'bug509', 'bug821', 'bug873', 'bug958', 'bug216', 'bug459', 'bug921', 'bug35', 'bug387', 'bug680', 'bug1181', 'bug1040', 'bug639', 'bug0', 'bug1081', 'bug470', 'bug1057', 'bug919', 'bug949', 'bug1164', 'bug867', 'bug39', 'bug236', 'bug575', 'bug1048', 'bug420', 'bug1173', 'bug1140', 'bug546', 'bug700', 'bug195', 'bug684', 'bug183', 'bug372', 'bug1053', 'bug936', 'bug248', 'bug888', 'bug667', 'bug1157', 'bug513', 'bug196', 'bug837', 'bug1136', 'bug611', 'bug88', 'bug262', 'bug1143', 'bug8', 'bug1148', 'bug1109', 'bug685', 'bug245', 'bug244', 'bug1179', 'bug453', 'bug107', 'bug690', 'bug224', 'bug37', 'bug670', 'bug399', 'bug557', 'bug1451', 'bug1084', 'bug746', 'bug61', 'bug12', 'bug82

['bug722', 'bug74', 'bug797', 'bug57', 'bug274', 'bug769', 'bug407', 'bug163', 'bug879', 'bug1600', 'bug378', 'bug205', 'bug236', 'bug1029', 'bug326', 'bug717', 'bug583', 'bug1187', 'bug221', 'bug569', 'bug1077', 'bug660', 'bug125', 'bug924', 'bug433', 'bug669', 'bug632', 'bug1101', 'bug547', 'bug362', 'bug551', 'bug795', 'bug331', 'bug772', 'bug382', 'bug124', 'bug373', 'bug596', 'bug226', 'bug306', 'bug567', 'bug1191', 'bug656', 'bug1005', 'bug893', 'bug381', 'bug105', 'bug649', 'bug799', 'bug293', 'bug1509', 'bug300', 'bug483', 'bug997', 'bug601', 'bug1168', 'bug758', 'bug317', 'bug179', 'bug748', 'bug107', 'bug965', 'bug695', 'bug951', 'bug161', 'bug771', 'bug725', 'bug9', 'bug499', 'bug779', 'bug478', 'bug345', 'bug898', 'bug1164', 'bug854', 'bug23', 'bug1087', 'bug741', 'bug1194', 'bug1009', 'bug593', 'bug887', 'bug710', 'bug1120', 'bug908', 'bug979', 'bug327', 'bug776', 'bug1070', 'bug190', 'bug823', 'bug188', 'bug835', 'bug1024', 'bug285', 'bug308', 'bug420', 'bug174', 'bug240'

['bug2274', 'bug1046', 'bug1174', 'bug390', 'bug143', 'bug987', 'bug486', 'bug549', 'bug1011', 'bug259', 'bug617', 'bug1745', 'bug1074', 'bug42', 'bug38', 'bug434', 'bug213', 'bug559', 'bug578', 'bug894', 'bug616', 'bug666', 'bug855', 'bug655', 'bug394', 'bug2355', 'bug624', 'bug568', 'bug1090', 'bug904', 'bug770', 'bug902', 'bug730', 'bug738', 'bug273', 'bug152', 'bug1175', 'bug585', 'bug1142', 'bug911', 'bug209', 'bug724', 'bug741', 'bug407', 'bug690', 'bug679', 'bug353', 'bug776', 'bug455', 'bug173', 'bug182', 'bug70', 'bug792', 'bug58', 'bug315', 'bug677', 'bug521', 'bug1015', 'bug266', 'bug87', 'bug872', 'bug282', 'bug534', 'bug392', 'bug662', 'bug175', 'bug1191', 'bug1088', 'bug108', 'bug924', 'bug696', 'bug106', 'bug256', 'bug647', 'bug322', 'bug35', 'bug874', 'bug1106', 'bug879', 'bug1176', 'bug1136', 'bug1100', 'bug518', 'bug300', 'bug437', 'bug1182', 'bug664', 'bug344', 'bug188', 'bug1188', 'bug129', 'bug435', 'bug996', 'bug373', 'bug691', 'bug286', 'bug612', 'bug422', 'bug10

['bug501', 'bug1045', 'bug1171', 'bug1061', 'bug455', 'bug98', 'bug477', 'bug951', 'bug169', 'bug906', 'bug338', 'bug792', 'bug820', 'bug717', 'bug780', 'bug903', 'bug432', 'bug718', 'bug360', 'bug940', 'bug880', 'bug1082', 'bug1469', 'bug1035', 'bug110', 'bug847', 'bug1122', 'bug56', 'bug1154', 'bug388', 'bug322', 'bug841', 'bug960', 'bug564', 'bug343', 'bug318', 'bug1192', 'bug364', 'bug280', 'bug937', 'bug1094', 'bug1410', 'bug484', 'bug835', 'bug283', 'bug461', 'bug802', 'bug643', 'bug499', 'bug798', 'bug272', 'bug1066', 'bug375', 'bug17', 'bug545', 'bug95', 'bug25', 'bug999', 'bug784', 'bug709', 'bug243', 'bug1033', 'bug2399', 'bug1130', 'bug719', 'bug327', 'bug1093', 'bug949', 'bug204', 'bug824', 'bug194', 'bug876', 'bug688', 'bug1077', 'bug53', 'bug493', 'bug222', 'bug1018', 'bug350', 'bug452', 'bug475', 'bug911', 'bug822', 'bug463', 'bug704', 'bug341', 'bug398', 'bug1144', 'bug528', 'bug516', 'bug195', 'bug459', 'bug935', 'bug443', 'bug936', 'bug14', 'bug952', 'bug603', 'bug712

['bug752', 'bug1096', 'bug889', 'bug236', 'bug1107', 'bug226', 'bug517', 'bug218', 'bug451', 'bug76', 'bug408', 'bug3', 'bug541', 'bug696', 'bug751', 'bug215', 'bug237', 'bug1034', 'bug577', 'bug786', 'bug555', 'bug1186', 'bug174', 'bug357', 'bug929', 'bug12', 'bug1043', 'bug1016', 'bug745', 'bug365', 'bug1170', 'bug917', 'bug757', 'bug79', 'bug296', 'bug681', 'bug882', 'bug1118', 'bug1150', 'bug1011', 'bug775', 'bug0', 'bug1656', 'bug890', 'bug1020', 'bug844', 'bug838', 'bug622', 'bug6', 'bug525', 'bug1068', 'bug614', 'bug295', 'bug1072', 'bug418', 'bug877', 'bug1113', 'bug595', 'bug172', 'bug946', 'bug70', 'bug117', 'bug1808', 'bug60', 'bug385', 'bug784', 'bug356', 'bug1103', 'bug596', 'bug624', 'bug1021', 'bug873', 'bug1003', 'bug1167', 'bug1163', 'bug813', 'bug125', 'bug689', 'bug942', 'bug677', 'bug2391', 'bug334', 'bug360', 'bug279', 'bug513', 'bug1088', 'bug54', 'bug161', 'bug771', 'bug638', 'bug302', 'bug998', 'bug30', 'bug1017', 'bug1127', 'bug950', 'bug359', 'bug763', 'bug340

['bug526', 'bug322', 'bug1581', 'bug602', 'bug845', 'bug561', 'bug2346', 'bug275', 'bug631', 'bug392', 'bug642', 'bug1031', 'bug729', 'bug459', 'bug149', 'bug969', 'bug605', 'bug56', 'bug656', 'bug118', 'bug815', 'bug386', 'bug136', 'bug329', 'bug25', 'bug63', 'bug1112', 'bug105', 'bug985', 'bug146', 'bug462', 'bug111', 'bug117', 'bug1005', 'bug600', 'bug974', 'bug675', 'bug197', 'bug440', 'bug2399', 'bug353', 'bug660', 'bug1028', 'bug76', 'bug315', 'bug17', 'bug574', 'bug58', 'bug1010', 'bug488', 'bug463', 'bug492', 'bug470', 'bug1045', 'bug319', 'bug423', 'bug355', 'bug375', 'bug999', 'bug1145', 'bug403', 'bug994', 'bug387', 'bug1167', 'bug619', 'bug369', 'bug487', 'bug1019', 'bug629', 'bug382', 'bug787', 'bug62', 'bug1095', 'bug1142', 'bug911', 'bug1155', 'bug252', 'bug1098', 'bug429', 'bug241', 'bug991', 'bug914', 'bug1553', 'bug1176', 'bug960', 'bug1162', 'bug212', 'bug104', 'bug862', 'bug195', 'bug433', 'bug67', 'bug318', 'bug224', 'bug243', 'bug859', 'bug209', 'bug414', 'bug37',

['bug26', 'bug1122', 'bug1056', 'bug747', 'bug815', 'bug283', 'bug1199', 'bug977', 'bug642', 'bug927', 'bug951', 'bug62', 'bug999', 'bug1103', 'bug829', 'bug1185', 'bug338', 'bug980', 'bug1088', 'bug1042', 'bug678', 'bug1080', 'bug748', 'bug709', 'bug676', 'bug380', 'bug604', 'bug600', 'bug328', 'bug761', 'bug1022', 'bug647', 'bug1095', 'bug327', 'bug106', 'bug15', 'bug856', 'bug413', 'bug302', 'bug129', 'bug933', 'bug875', 'bug461', 'bug75', 'bug318', 'bug1087', 'bug1144', 'bug807', 'bug56', 'bug350', 'bug1099', 'bug136', 'bug1048', 'bug755', 'bug29', 'bug1005', 'bug582', 'bug383', 'bug332', 'bug566', 'bug978', 'bug630', 'bug788', 'bug357', 'bug936', 'bug1154', 'bug1050', 'bug798', 'bug975', 'bug1126', 'bug988', 'bug425', 'bug1810', 'bug205', 'bug816', 'bug1195', 'bug206', 'bug1068', 'bug789', 'bug947', 'bug1180', 'bug796', 'bug1163', 'bug560', 'bug288', 'bug484', 'bug299', 'bug578', 'bug431', 'bug412', 'bug30', 'bug98', 'bug855', 'bug1052', 'bug677', 'bug1064', 'bug537', 'bug289', 'b

['bug1656', 'bug640', 'bug880', 'bug500', 'bug84', 'bug323', 'bug669', 'bug733', 'bug211', 'bug621', 'bug1151', 'bug602', 'bug151', 'bug42', 'bug769', 'bug414', 'bug1180', 'bug365', 'bug552', 'bug1165', 'bug905', 'bug1065', 'bug78', 'bug503', 'bug540', 'bug376', 'bug486', 'bug1063', 'bug257', 'bug730', 'bug1195', 'bug401', 'bug1098', 'bug1020', 'bug1726', 'bug308', 'bug6', 'bug611', 'bug2399', 'bug618', 'bug1157', 'bug453', 'bug990', 'bug10', 'bug159', 'bug171', 'bug870', 'bug1022', 'bug963', 'bug355', 'bug589', 'bug45', 'bug92', 'bug129', 'bug345', 'bug307', 'bug383', 'bug883', 'bug454', 'bug624', 'bug111', 'bug462', 'bug7', 'bug353', 'bug393', 'bug642', 'bug337', 'bug714', 'bug463', 'bug683', 'bug1217', 'bug139', 'bug17', 'bug759', 'bug1154', 'bug71', 'bug265', 'bug395', 'bug783', 'bug9', 'bug592', 'bug480', 'bug1009', 'bug260', 'bug93', 'bug318', 'bug586', 'bug646', 'bug756', 'bug76', 'bug630', 'bug806', 'bug1118', 'bug984', 'bug1031', 'bug160', 'bug931', 'bug825', 'bug132', 'bug582

['bug1162', 'bug1035', 'bug119', 'bug509', 'bug272', 'bug128', 'bug841', 'bug192', 'bug84', 'bug390', 'bug1039', 'bug729', 'bug1104', 'bug588', 'bug35', 'bug476', 'bug564', 'bug1044', 'bug304', 'bug414', 'bug1137', 'bug241', 'bug396', 'bug774', 'bug754', 'bug10', 'bug33', 'bug801', 'bug532', 'bug246', 'bug787', 'bug393', 'bug1083', 'bug384', 'bug1103', 'bug2092', 'bug226', 'bug601', 'bug69', 'bug157', 'bug998', 'bug1127', 'bug288', 'bug32', 'bug448', 'bug1079', 'bug328', 'bug44', 'bug1178', 'bug219', 'bug210', 'bug1029', 'bug274', 'bug1151', 'bug104', 'bug409', 'bug590', 'bug352', 'bug222', 'bug943', 'bug245', 'bug445', 'bug1098', 'bug385', 'bug43', 'bug446', 'bug840', 'bug1066', 'bug76', 'bug572', 'bug748', 'bug648', 'bug742', 'bug751', 'bug1004', 'bug287', 'bug888', 'bug206', 'bug1072', 'bug654', 'bug300', 'bug281', 'bug2399', 'bug608', 'bug484', 'bug388', 'bug196', 'bug551', 'bug725', 'bug497', 'bug333', 'bug962', 'bug389', 'bug81', 'bug395', 'bug747', 'bug940', 'bug1037', 'bug842',

['bug535', 'bug652', 'bug1800', 'bug89', 'bug1056', 'bug821', 'bug300', 'bug939', 'bug285', 'bug850', 'bug513', 'bug601', 'bug1147', 'bug70', 'bug1004', 'bug755', 'bug720', 'bug226', 'bug59', 'bug398', 'bug279', 'bug170', 'bug259', 'bug92', 'bug133', 'bug222', 'bug547', 'bug968', 'bug234', 'bug36', 'bug365', 'bug629', 'bug187', 'bug1010', 'bug827', 'bug264', 'bug188', 'bug220', 'bug556', 'bug509', 'bug293', 'bug924', 'bug820', 'bug446', 'bug97', 'bug734', 'bug988', 'bug225', 'bug617', 'bug846', 'bug157', 'bug618', 'bug900', 'bug598', 'bug1864', 'bug488', 'bug134', 'bug611', 'bug304', 'bug646', 'bug356', 'bug257', 'bug341', 'bug746', 'bug314', 'bug534', 'bug962', 'bug839', 'bug576', 'bug204', 'bug299', 'bug139', 'bug1127', 'bug631', 'bug723', 'bug971', 'bug112', 'bug472', 'bug207', 'bug822', 'bug974', 'bug784', 'bug756', 'bug925', 'bug177', 'bug940', 'bug364', 'bug783', 'bug737', 'bug98', 'bug1115', 'bug609', 'bug319', 'bug759', 'bug779', 'bug128', 'bug615', 'bug463', 'bug715', 'bug1040

['bug260', 'bug1045', 'bug369', 'bug573', 'bug1007', 'bug1099', 'bug419', 'bug365', 'bug583', 'bug629', 'bug1069', 'bug855', 'bug361', 'bug67', 'bug1184', 'bug822', 'bug881', 'bug722', 'bug57', 'bug523', 'bug789', 'bug971', 'bug252', 'bug127', 'bug229', 'bug72', 'bug1001', 'bug667', 'bug7', 'bug799', 'bug808', 'bug530', 'bug281', 'bug572', 'bug400', 'bug378', 'bug121', 'bug837', 'bug603', 'bug352', 'bug570', 'bug766', 'bug992', 'bug1059', 'bug919', 'bug1125', 'bug569', 'bug118', 'bug23', 'bug776', 'bug839', 'bug397', 'bug1075', 'bug465', 'bug640', 'bug2151', 'bug922', 'bug3', 'bug920', 'bug300', 'bug153', 'bug1181', 'bug58', 'bug110', 'bug713', 'bug1121', 'bug1018', 'bug619', 'bug56', 'bug446', 'bug131', 'bug944', 'bug950', 'bug262', 'bug557', 'bug1161', 'bug1183', 'bug759', 'bug392', 'bug638', 'bug473', 'bug1068', 'bug0', 'bug305', 'bug761', 'bug737', 'bug406', 'bug313', 'bug62', 'bug59', 'bug1145', 'bug582', 'bug371', 'bug211', 'bug533', 'bug50', 'bug957', 'bug1076', 'bug99', 'bug190

['bug979', 'bug1140', 'bug487', 'bug894', 'bug993', 'bug372', 'bug355', 'bug887', 'bug677', 'bug387', 'bug15', 'bug586', 'bug531', 'bug925', 'bug198', 'bug611', 'bug910', 'bug31', 'bug589', 'bug1074', 'bug458', 'bug352', 'bug1183', 'bug672', 'bug696', 'bug248', 'bug913', 'bug941', 'bug84', 'bug934', 'bug948', 'bug949', 'bug316', 'bug116', 'bug720', 'bug14', 'bug548', 'bug1171', 'bug27', 'bug1030', 'bug249', 'bug546', 'bug783', 'bug829', 'bug1962', 'bug99', 'bug921', 'bug113', 'bug535', 'bug500', 'bug123', 'bug1883', 'bug86', 'bug215', 'bug585', 'bug805', 'bug73', 'bug348', 'bug885', 'bug754', 'bug1011', 'bug503', 'bug603', 'bug1066', 'bug332', 'bug638', 'bug488', 'bug523', 'bug727', 'bug494', 'bug1045', 'bug1005', 'bug473', 'bug242', 'bug682', 'bug668', 'bug283', 'bug923', 'bug493', 'bug763', 'bug1196', 'bug490', 'bug193', 'bug169', 'bug726', 'bug786', 'bug287', 'bug845', 'bug844', 'bug491', 'bug400', 'bug397', 'bug599', 'bug18', 'bug47', 'bug605', 'bug1136', 'bug896', 'bug1001', 'bug6

['bug983', 'bug390', 'bug1120', 'bug370', 'bug746', 'bug1105', 'bug164', 'bug440', 'bug514', 'bug913', 'bug0', 'bug772', 'bug886', 'bug305', 'bug592', 'bug2399', 'bug1136', 'bug854', 'bug683', 'bug849', 'bug708', 'bug850', 'bug493', 'bug817', 'bug262', 'bug1034', 'bug331', 'bug268', 'bug1074', 'bug68', 'bug625', 'bug481', 'bug1063', 'bug306', 'bug977', 'bug531', 'bug1173', 'bug1007', 'bug119', 'bug1097', 'bug629', 'bug833', 'bug727', 'bug162', 'bug249', 'bug206', 'bug905', 'bug200', 'bug648', 'bug813', 'bug859', 'bug154', 'bug964', 'bug940', 'bug975', 'bug418', 'bug677', 'bug881', 'bug966', 'bug614', 'bug490', 'bug160', 'bug1163', 'bug289', 'bug489', 'bug657', 'bug558', 'bug158', 'bug1044', 'bug1054', 'bug671', 'bug423', 'bug421', 'bug475', 'bug486', 'bug322', 'bug989', 'bug13', 'bug161', 'bug1109', 'bug91', 'bug85', 'bug603', 'bug866', 'bug710', 'bug788', 'bug587', 'bug69', 'bug785', 'bug653', 'bug1028', 'bug729', 'bug1002', 'bug64', 'bug517', 'bug227', 'bug1058', 'bug120', 'bug52', '

['bug321', 'bug881', 'bug329', 'bug657', 'bug601', 'bug885', 'bug814', 'bug485', 'bug786', 'bug927', 'bug879', 'bug420', 'bug642', 'bug109', 'bug1756', 'bug921', 'bug294', 'bug594', 'bug1061', 'bug915', 'bug781', 'bug787', 'bug762', 'bug741', 'bug808', 'bug92', 'bug937', 'bug1001', 'bug1045', 'bug735', 'bug759', 'bug519', 'bug1145', 'bug719', 'bug417', 'bug527', 'bug774', 'bug539', 'bug225', 'bug997', 'bug1405', 'bug882', 'bug876', 'bug987', 'bug1460', 'bug503', 'bug115', 'bug1036', 'bug462', 'bug178', 'bug1179', 'bug968', 'bug1033', 'bug720', 'bug469', 'bug630', 'bug224', 'bug289', 'bug858', 'bug994', 'bug1158', 'bug679', 'bug904', 'bug1083', 'bug1110', 'bug856', 'bug912', 'bug1187', 'bug484', 'bug945', 'bug1133', 'bug1049', 'bug141', 'bug238', 'bug291', 'bug1106', 'bug939', 'bug325', 'bug1183', 'bug400', 'bug371', 'bug663', 'bug551', 'bug406', 'bug395', 'bug900', 'bug111', 'bug41', 'bug1040', 'bug1138', 'bug131', 'bug623', 'bug1113', 'bug749', 'bug985', 'bug1164', 'bug243', 'bug483',

['bug940', 'bug847', 'bug1106', 'bug1179', 'bug1003', 'bug740', 'bug745', 'bug1115', 'bug122', 'bug693', 'bug1191', 'bug451', 'bug25', 'bug825', 'bug165', 'bug387', 'bug866', 'bug461', 'bug266', 'bug1193', 'bug295', 'bug969', 'bug1166', 'bug1135', 'bug652', 'bug82', 'bug599', 'bug1110', 'bug1117', 'bug434', 'bug1093', 'bug891', 'bug801', 'bug718', 'bug66', 'bug659', 'bug971', 'bug408', 'bug161', 'bug1058', 'bug45', 'bug87', 'bug731', 'bug1061', 'bug2092', 'bug1180', 'bug854', 'bug636', 'bug816', 'bug703', 'bug188', 'bug850', 'bug299', 'bug910', 'bug23', 'bug852', 'bug252', 'bug124', 'bug898', 'bug1142', 'bug68', 'bug330', 'bug951', 'bug80', 'bug195', 'bug803', 'bug1030', 'bug41', 'bug467', 'bug1075', 'bug346', 'bug968', 'bug961', 'bug78', 'bug733', 'bug907', 'bug571', 'bug221', 'bug172', 'bug900', 'bug723', 'bug17', 'bug1088', 'bug631', 'bug64', 'bug304', 'bug973', 'bug88', 'bug89', 'bug639', 'bug375', 'bug529', 'bug1063', 'bug999', 'bug586', 'bug174', 'bug515', 'bug1101', 'bug791', 'b

['bug2338', 'bug1581', 'bug1576', 'bug1290', 'bug576', 'bug1767', 'bug685', 'bug829', 'bug1045', 'bug71', 'bug1087', 'bug432', 'bug562', 'bug536', 'bug495', 'bug629', 'bug369', 'bug158', 'bug627', 'bug200', 'bug858', 'bug1098', 'bug1095', 'bug1124', 'bug373', 'bug83', 'bug67', 'bug837', 'bug349', 'bug864', 'bug733', 'bug299', 'bug439', 'bug1154', 'bug80', 'bug1177', 'bug779', 'bug1146', 'bug572', 'bug2', 'bug64', 'bug717', 'bug206', 'bug539', 'bug339', 'bug325', 'bug555', 'bug1131', 'bug297', 'bug990', 'bug926', 'bug966', 'bug707', 'bug822', 'bug551', 'bug845', 'bug416', 'bug624', 'bug636', 'bug96', 'bug473', 'bug386', 'bug394', 'bug574', 'bug192', 'bug126', 'bug1115', 'bug580', 'bug791', 'bug58', 'bug884', 'bug191', 'bug178', 'bug248', 'bug630', 'bug789', 'bug74', 'bug826', 'bug749', 'bug425', 'bug755', 'bug827', 'bug194', 'bug942', 'bug592', 'bug1079', 'bug517', 'bug147', 'bug640', 'bug124', 'bug854', 'bug388', 'bug167', 'bug947', 'bug830', 'bug862', 'bug232', 'bug746', 'bug477', 'bu

['bug1141', 'bug513', 'bug1648', 'bug593', 'bug722', 'bug600', 'bug191', 'bug318', 'bug1162', 'bug707', 'bug1126', 'bug474', 'bug450', 'bug1030', 'bug101', 'bug731', 'bug352', 'bug653', 'bug144', 'bug802', 'bug157', 'bug903', 'bug1004', 'bug225', 'bug270', 'bug462', 'bug331', 'bug739', 'bug17', 'bug786', 'bug866', 'bug317', 'bug223', 'bug696', 'bug725', 'bug1179', 'bug367', 'bug594', 'bug691', 'bug135', 'bug680', 'bug688', 'bug366', 'bug924', 'bug939', 'bug389', 'bug512', 'bug566', 'bug337', 'bug1104', 'bug210', 'bug238', 'bug235', 'bug970', 'bug1131', 'bug322', 'bug455', 'bug1014', 'bug36', 'bug58', 'bug760', 'bug167', 'bug648', 'bug916', 'bug63', 'bug1117', 'bug160', 'bug1127', 'bug1061', 'bug927', 'bug828', 'bug307', 'bug276', 'bug826', 'bug619', 'bug654', 'bug942', 'bug1020', 'bug149', 'bug550', 'bug528', 'bug147', 'bug446', 'bug1187', 'bug1130', 'bug190', 'bug902', 'bug959', 'bug29', 'bug122', 'bug657', 'bug872', 'bug583', 'bug511', 'bug951', 'bug546', 'bug1132', 'bug928', 'bug909

['bug1901', 'bug612', 'bug656', 'bug233', 'bug354', 'bug247', 'bug865', 'bug380', 'bug49', 'bug998', 'bug522', 'bug79', 'bug624', 'bug1048', 'bug914', 'bug927', 'bug1019', 'bug997', 'bug1010', 'bug444', 'bug363', 'bug821', 'bug408', 'bug226', 'bug356', 'bug758', 'bug203', 'bug684', 'bug731', 'bug825', 'bug288', 'bug641', 'bug945', 'bug1102', 'bug665', 'bug454', 'bug210', 'bug1137', 'bug1068', 'bug480', 'bug156', 'bug341', 'bug566', 'bug1168', 'bug1000', 'bug854', 'bug21', 'bug870', 'bug916', 'bug507', 'bug955', 'bug18', 'bug179', 'bug295', 'bug1079', 'bug639', 'bug818', 'bug623', 'bug757', 'bug1037', 'bug207', 'bug703', 'bug725', 'bug676', 'bug228', 'bug1786', 'bug342', 'bug73', 'bug15', 'bug11', 'bug931', 'bug208', 'bug358', 'bug302', 'bug221', 'bug140', 'bug537', 'bug883', 'bug1064', 'bug1153', 'bug595', 'bug0', 'bug188', 'bug10', 'bug693', 'bug102', 'bug479', 'bug53', 'bug529', 'bug6', 'bug582', 'bug71', 'bug622', 'bug805', 'bug1138', 'bug970', 'bug364', 'bug1186', 'bug647', 'bug95'

['bug505', 'bug848', 'bug459', 'bug220', 'bug75', 'bug190', 'bug86', 'bug460', 'bug914', 'bug169', 'bug296', 'bug399', 'bug424', 'bug68', 'bug736', 'bug1123', 'bug3', 'bug1059', 'bug272', 'bug301', 'bug207', 'bug1127', 'bug56', 'bug568', 'bug249', 'bug175', 'bug375', 'bug233', 'bug759', 'bug922', 'bug676', 'bug217', 'bug556', 'bug396', 'bug973', 'bug162', 'bug639', 'bug1023', 'bug154', 'bug1094', 'bug582', 'bug939', 'bug293', 'bug52', 'bug1196', 'bug637', 'bug181', 'bug1188', 'bug411', 'bug429', 'bug735', 'bug378', 'bug222', 'bug1192', 'bug686', 'bug804', 'bug982', 'bug230', 'bug1093', 'bug1041', 'bug913', 'bug297', 'bug1144', 'bug134', 'bug472', 'bug246', 'bug849', 'bug1136', 'bug120', 'bug1169', 'bug792', 'bug705', 'bug65', 'bug463', 'bug1379', 'bug935', 'bug490', 'bug651', 'bug70', 'bug1083', 'bug1033', 'bug718', 'bug617', 'bug755', 'bug82', 'bug319', 'bug304', 'bug94', 'bug143', 'bug1070', 'bug413', 'bug265', 'bug599', 'bug881', 'bug561', 'bug1116', 'bug340', 'bug332', 'bug780', 'b

['bug1175', 'bug1777', 'bug115', 'bug412', 'bug251', 'bug861', 'bug230', 'bug219', 'bug2274', 'bug374', 'bug987', 'bug680', 'bug1085', 'bug441', 'bug682', 'bug905', 'bug908', 'bug231', 'bug396', 'bug789', 'bug859', 'bug742', 'bug1048', 'bug811', 'bug247', 'bug75', 'bug1171', 'bug824', 'bug1137', 'bug497', 'bug909', 'bug1153', 'bug438', 'bug378', 'bug449', 'bug1185', 'bug437', 'bug548', 'bug165', 'bug459', 'bug483', 'bug1075', 'bug873', 'bug298', 'bug398', 'bug595', 'bug719', 'bug572', 'bug241', 'bug372', 'bug643', 'bug451', 'bug941', 'bug73', 'bug815', 'bug1008', 'bug108', 'bug982', 'bug464', 'bug534', 'bug812', 'bug1145', 'bug888', 'bug679', 'bug405', 'bug915', 'bug749', 'bug1046', 'bug7', 'bug1052', 'bug951', 'bug945', 'bug684', 'bug609', 'bug43', 'bug160', 'bug125', 'bug1014', 'bug797', 'bug269', 'bug949', 'bug630', 'bug1095', 'bug51', 'bug68', 'bug490', 'bug83', 'bug302', 'bug14', 'bug1063', 'bug831', 'bug503', 'bug432', 'bug198', 'bug191', 'bug618', 'bug750', 'bug471', 'bug61', 'b

['bug154', 'bug1594', 'bug1166', 'bug724', 'bug831', 'bug628', 'bug1458', 'bug544', 'bug24', 'bug54', 'bug563', 'bug668', 'bug575', 'bug508', 'bug1112', 'bug529', 'bug483', 'bug613', 'bug1045', 'bug498', 'bug970', 'bug393', 'bug1007', 'bug644', 'bug515', 'bug282', 'bug158', 'bug440', 'bug681', 'bug889', 'bug592', 'bug473', 'bug907', 'bug525', 'bug579', 'bug1120', 'bug1037', 'bug701', 'bug627', 'bug1142', 'bug251', 'bug940', 'bug1165', 'bug780', 'bug203', 'bug220', 'bug1082', 'bug478', 'bug633', 'bug615', 'bug608', 'bug1198', 'bug250', 'bug369', 'bug865', 'bug828', 'bug987', 'bug882', 'bug28', 'bug1128', 'bug807', 'bug376', 'bug444', 'bug2162', 'bug926', 'bug268', 'bug915', 'bug1172', 'bug407', 'bug914', 'bug382', 'bug1054', 'bug586', 'bug94', 'bug1099', 'bug291', 'bug986', 'bug909', 'bug1143', 'bug1048', 'bug368', 'bug852', 'bug1113', 'bug1059', 'bug427', 'bug217', 'bug27', 'bug212', 'bug332', 'bug620', 'bug540', 'bug811', 'bug55', 'bug316', 'bug635', 'bug470', 'bug246', 'bug583', 'bug

['bug258', 'bug1278', 'bug596', 'bug262', 'bug1077', 'bug1872', 'bug851', 'bug1054', 'bug804', 'bug846', 'bug277', 'bug736', 'bug791', 'bug419', 'bug617', 'bug825', 'bug997', 'bug50', 'bug25', 'bug118', 'bug412', 'bug1020', 'bug1038', 'bug263', 'bug411', 'bug687', 'bug223', 'bug605', 'bug467', 'bug417', 'bug857', 'bug923', 'bug2399', 'bug976', 'bug991', 'bug89', 'bug954', 'bug1089', 'bug283', 'bug1004', 'bug31', 'bug788', 'bug696', 'bug1107', 'bug877', 'bug613', 'bug425', 'bug692', 'bug882', 'bug758', 'bug159', 'bug912', 'bug943', 'bug835', 'bug891', 'bug800', 'bug865', 'bug745', 'bug859', 'bug197', 'bug583', 'bug1006', 'bug965', 'bug1141', 'bug1078', 'bug1056', 'bug363', 'bug1007', 'bug833', 'bug323', 'bug463', 'bug445', 'bug1183', 'bug361', 'bug1066', 'bug92', 'bug429', 'bug641', 'bug675', 'bug983', 'bug10', 'bug953', 'bug132', 'bug1034', 'bug1039', 'bug936', 'bug870', 'bug394', 'bug628', 'bug278', 'bug337', 'bug2092', 'bug834', 'bug863', 'bug948', 'bug330', 'bug1057', 'bug389', 'bug

In [95]:
for i in range(len(bugs)):
    print(bugs["bug"+str(i)]["score"])


[[0.89693264]]
[[1.28959084]]
[[0.83946771]]
[[0.8385097]]
[[0.83336773]]
[[0.93198815]]
[[0.83013617]]
[[0.89545275]]
[[0.82979183]]
[[0.85240443]]
[[0.70635009]]
[[1.24210032]]
[[0.8443256]]
[[0.80868388]]
[[0.83948896]]
[[3.7794995]]
[[0.85436164]]
[[0.83952651]]
[[0.81399442]]
[[0.84997197]]
[[0.84774152]]
[[0.84180075]]
[[1.37297432]]
[[0.82250768]]
[[0.84181826]]
[[0.64602654]]
[[1.3036248]]
[[1.39847197]]
[[1.33966667]]
[[0.97650064]]
[[2.24976634]]
[[0.66645177]]
[[0.84558909]]
[[0.83517404]]
[[0.84356433]]
[[0.73414561]]
[[0.84018975]]
[[0.83187864]]
[[0.76859119]]
[[0.8447493]]
[[0.89966415]]
[[0.90336231]]
[[0.84333857]]
[[0.83860867]]
[[0.89938024]]
[[0.8669003]]
[[0.83852776]]
[[0.85209092]]
[[1.44268361]]
[[0.83875435]]
[[0.64588283]]
[[0.83721394]]
[[0.73449905]]
[[0.87163938]]
[[0.83849841]]
[[1.39451472]]
[[0.85565291]]
[[0.83143287]]
[[0.84523989]]
[[0.85429417]]
[[0.88902706]]
[[0.8488555]]
[[0.84300873]]
[[0.83849579]]
[[0.83256785]]
[[0.74521377]]
[[1.37321182]]
[[

[[0.84357681]]
[[0.84194899]]
[[0.83849919]]
[[0.92153671]]
[[0.78887983]]
[[0.88019596]]
[[0.68497229]]
[[0.84772648]]
[[0.88003117]]
[[0.82199761]]
[[3.96967098]]
[[0.81494707]]
[[0.83816342]]
[[0.91768248]]
[[0.84272607]]
[[0.88357009]]
[[0.8290735]]
[[1.15438855]]
[[0.94615493]]
[[0.84082774]]
[[0.84516635]]
[[0.84019593]]
[[0.83973261]]
[[0.83373986]]
[[0.83935324]]
[[0.84909515]]
[[0.83856045]]
[[0.68119708]]
[[0.83849081]]
[[0.83850178]]
[[0.90028529]]
[[0.84332737]]
[[0.8387511]]
[[0.740656]]
[[0.83876396]]
[[0.80133134]]
[[0.83861229]]
[[0.87020013]]
[[0.65999243]]
[[0.84812026]]
[[0.85240648]]
[[0.84867798]]
[[1.16942635]]
[[0.86005942]]
[[0.84491348]]
[[0.85214449]]
[[1.33025358]]
[[0.84041093]]
[[0.86728573]]
[[0.93140699]]
[[1.34860333]]
[[0.7076896]]
[[0.83226549]]
[[0.84830862]]
[[0.84364148]]
[[0.80825001]]
[[0.84568494]]
[[0.8599516]]
[[0.6837406]]
[[0.86838528]]
[[0.8320624]]
[[1.1649497]]
[[0.83857367]]
[[0.72062272]]
[[0.83409725]]
[[0.76230208]]
[[0.84360607]]
[[0.

[[11.51061884]]
[[10.34387163]]
[[34.11512611]]
[[0.58010678]]
[[2.25221133]]
[[27.41596339]]
[[19.20906394]]
[[0.84568253]]
[[2.16513291]]
[[5.65157195]]
[[7.06702847]]
[[1.42105933]]
[[17.29191469]]
[[21.20184479]]
[[0.87068785]]
[[1.20024297]]
[[0.81372979]]
[[12.13698384]]
[[7.93254442]]
[[4.39656234]]
[[31.03006196]]
[[3.67066886]]
[[34.42885817]]
[[13.14592845]]
[[14.81248339]]
[[24.09866416]]
[[2.1491685]]
[[12.23574447]]
[[20.56187508]]
[[1.55084737]]
[[26.94872374]]
[[13.65350338]]
[[4.81939382]]
[[26.56651689]]
[[20.79858763]]
[[28.97404832]]
[[3.1283224]]
[[10.69179107]]
[[12.18813497]]
[[1.785638]]
[[32.84322363]]
[[10.67215723]]
[[16.80521982]]
[[14.40867502]]
[[5.96482904]]
[[11.0639786]]
[[7.88291123]]
[[11.26930972]]
[[4.58816505]]
[[22.44667292]]
[[43.82977304]]
[[16.74887225]]
[[19.08711379]]
[[22.06477458]]
[[4.96062991]]
[[11.8296767]]
[[39.3678498]]
[[17.48313531]]
[[45.32885902]]
[[19.99825294]]
[[1.90595956]]
[[9.27905794]]
[[8.46076685]]
[[30.23886201]]
[[4.6883

In [22]:

food = make_food(10)
data_length =food["fo0"].shape[0] + 4 #(This 4 is symbolizes the four direction of movement)
num_data = len(food)

bugs = make_bugs(1,48,4,data_length,num_data)


'''print("Gen W1" ,bugs["bug0"]["W1"])
print("Gen b1",bugs["bug0"]["b1"])
print("Gen W2", bugs["bug0"]["W2"])
print("Gen b2", bugs["bug0"]["b2"])
print("Gen W3", bugs["bug0"]["decider_W3"])
print("Gen b3", bugs["bug0"]["decider_b3"])'''


'''print("Gen W1" ,bugs["bug22"]["W1"])
print("Gen b1",bugs["bug22"]["b1"])
print("Gen W2", bugs["bug22"]["W2"])
print("Gen b2", bugs["bug22"]["b2"])
print("Gen W3", bugs["bug22"]["decider_W3"])
print("Gen b3", bugs["bug22"]["decider_b3"])
'''

print("Gen W1" ,bugs["bug41"]["W1"])
print("Gen b1",bugs["bug41"]["b1"])
print("Gen W2", bugs["bug41"]["W2"])
print("Gen b2", bugs["bug41"]["b2"])
print("Gen W3", bugs["bug41"]["decider_W3"])
print("Gen b3", bugs["bug41"]["decider_b3"])


movement_points = all_the_bugs_deciding(bugs,food)
#print(movement_points)


#print("beginning: " ,bugs["bug0"]["coordinates"])
move_all_the_bugs(bugs,movement_points)
#print("last: " ,bugs["bug0"]["coordinates"])
#print("movement:" ,movement_points["bug0"])

evaluating_bugs(bugs,food)

survivor_names = natural_selection(bugs,food)
#print(survivor_names)

gene_bag = the_big_shuffler(bugs,survivor_names)
#print(gene_bag)

bugs = single_cell_create(bugs,gene_bag)
'''print("nextGen W1" ,bugs["bug0"]["W1"])
print("nextGen b1",bugs["bug0"]["b1"])
print("nextGen W2", bugs["bug0"]["W2"])
print("nextGen b2", bugs["bug0"]["b2"])
print("nextGen W3", bugs["bug0"]["decider_W3"])
print("nextGen b3", bugs["bug0"]["decider_b3"])'''


bugs = two_cell_create(bugs,gene_bag)

'''print("nextGen W1" ,bugs["bug22"]["W1"])
print("nextGen b1",bugs["bug22"]["b1"])
print("nextGen W2", bugs["bug22"]["W2"])
print("nextGen b2", bugs["bug22"]["b2"])
print("nextGen W3", bugs["bug22"]["decider_W3"])
print("nextGen b3", bugs["bug22"]["decider_b3"])
'''

bugs = four_cell_create(bugs,gene_bag)

print("nextGen W1" ,bugs["bug41"]["W1"])
print("nextGen b1",bugs["bug41"]["b1"])
print("nextGen W2", bugs["bug41"]["W2"])
print("nextGen b2", bugs["bug41"]["b2"])
print("nextGen W3", bugs["bug41"]["decider_W3"])
print("nextGen b3", bugs["bug41"]["decider_b3"])



Gen W1 [[-0.4004796  -1.26129403 -0.449756   -0.02261191 -0.71332656 -0.76475869
  -0.60024928 -0.66130513]
 [-0.77903903  0.99843736  1.04720988 -0.06004121  1.48422958  0.34050947
  -0.01367009  0.66446829]
 [ 0.72178606 -0.40635409 -0.68991746 -0.22515122 -2.10337327 -1.28069867
   0.16403747 -0.95770685]
 [-1.36467884  0.57184914  1.33461932  0.1010944   0.77626857 -0.86912554
  -0.68868606  2.59231445]]
Gen b1 [[0.]
 [0.]
 [0.]
 [0.]]
Gen W2 [[-0.91386424 -2.18081946 -0.66123703 -0.06840691]
 [ 1.77884592 -1.3442653  -1.49901742  0.09682976]
 [-1.07222061  0.20107586  1.07929083  1.43367419]
 [ 0.88257624  0.70425436  0.12504735 -0.9645607 ]]
Gen b2 [[0.]
 [0.]
 [0.]
 [0.]]
Gen W3 [[-0.00857711  0.27236544  0.01280088  1.72911103 -1.06843791 -0.13964534
   0.19486949 -0.16106157 -1.71281416  0.33216272]]
Gen b3 [[0.]]
nextGen W1 [[ 0.02715842  0.41516042 -0.56379084 -0.3289123   0.00562478  0.08614645
  -0.54755219 -1.755171  ]
 [ 1.47554773  0.23382935  1.36606843 -1.09835465 -0.

[[1.]
 [1.]
 [1.]
 [1.]]


In [42]:



'''print("Gen W1" ,bugs["bug0"]["W1"])
print("Gen b1",bugs["bug0"]["b1"])
print("Gen W2", bugs["bug0"]["W2"])
print("Gen b2", bugs["bug0"]["b2"])
print("Gen W3", bugs["bug0"]["decider_W3"])
print("Gen b3", bugs["bug0"]["decider_b3"])'''


'''print("Gen W1" ,bugs["bug22"]["W1"])
print("Gen b1",bugs["bug22"]["b1"])
print("Gen W2", bugs["bug22"]["W2"])
print("Gen b2", bugs["bug22"]["b2"])
print("Gen W3", bugs["bug22"]["decider_W3"])
print("Gen b3", bugs["bug22"]["decider_b3"])
'''



movement_points = all_the_bugs_deciding(bugs,food)
#print(movement_points)


#print("beginning: " ,bugs["bug0"]["coordinates"])
move_all_the_bugs(bugs,movement_points)
#print("last: " ,bugs["bug0"]["coordinates"])
#print("movement:" ,movement_points["bug0"])

evaluating_bugs(bugs,food)

survivor_names = natural_selection(bugs,food)
print(survivor_names)

gene_bag = the_big_shuffler(bugs,survivor_names)
#print(gene_bag)

bugs = single_cell_create(bugs,gene_bag)
'''print("nextGen W1" ,bugs["bug0"]["W1"])
print("nextGen b1",bugs["bug0"]["b1"])
print("nextGen W2", bugs["bug0"]["W2"])
print("nextGen b2", bugs["bug0"]["b2"])
print("nextGen W3", bugs["bug0"]["decider_W3"])
print("nextGen b3", bugs["bug0"]["decider_b3"])'''


bugs = two_cell_create(bugs,gene_bag)

'''print("nextGen W1" ,bugs["bug22"]["W1"])
print("nextGen b1",bugs["bug22"]["b1"])
print("nextGen W2", bugs["bug22"]["W2"])
print("nextGen b2", bugs["bug22"]["b2"])
print("nextGen W3", bugs["bug22"]["decider_W3"])
print("nextGen b3", bugs["bug22"]["decider_b3"])
'''

bugs = four_cell_create(bugs,gene_bag)




['bug4', 'bug13', 'bug15', 'bug2']


In [15]:
a = random.randint(0,7)
print(a)

gene = gene_bag["layer_1_cells_W1"][a]
#print(gene)
a = random.randint(0,7)
gene2 = gene_bag["layer_1_cells_W1"][a]
a = random.randint(0,7)
gene3 = gene_bag["layer_1_cells_W1"][a]

liste = [gene,gene2,gene3]
#final = np.concatenate((gene.reshape(1,8),gene2.reshape(1,8)),axis = 0)
#print(final.shape)
vistack = np.vstack(liste)
print(vistack.shape)

1
(3, 8)


In [12]:
a = np.array([1,1,1,1,1,1,1,1])
b = bugs["bug0"]["W1"]
c = bugs["bug0"]["W2"]
d = bugs["bug0"]["decider_W3"]
print(np.dot(d,np.dot(c,np.dot(b,a))).shape)

ValueError: shapes (1,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)

(0,)


In [33]:
first =np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(first.shape)

a = np.array([2,2,2,2])
a = a.reshape(a.shape[0],1)
k = np.ones([first.shape[0],first.shape[1]])

second = k.T*a
print(second)
print(second.shape)

result = np.append(first.T,second,axis =0)

print(result)
print(result.shape)

(3, 4)
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
(4, 3)
[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6.  9.]
 [ 4.  7. 10.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
(8, 3)


In [41]:
print(result[0:2,:])
print(result)

[[1. 4. 7.]
 [2. 5. 8.]]
[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6.  9.]
 [ 4.  7. 10.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
